### ISSUE TITLE
INFO: Where to get ffmpeg after September 18, 2020?

### ISSUE THREAD

**Issue by PeterCodar** [0x90d/videoduplicatefinder#107]
Just to let you know:

ffmpeg.zeranoe.com shows currently:

> ffmpeg.zeranoe.com will close on Sep 18, 2020, and **all builds will be removed**. If you're using Zeranoe FFmpeg Builds in your product, please ensure that you have a hosting strategy in place by the 18th. Thank you to everyone who supported the project along the way!

Does anyone know a successor site?
Where do we get actual ffmpeg builds after September 18, 2020?

**Comment by Revan654** [comment]
> Just to let you know:
> 
> ffmpeg.zeranoe.com shows currently:
> 
> > ffmpeg.zeranoe.com will close on Sep 18, 2020, and **all builds will be removed**. If you're using Zeranoe FFmpeg Builds in your product, please ensure that you have a hosting strategy in place by the 18th. Thank you to everyone who supported the project along the way!
> 
> Does anyone know a successor site?
> Where do we get actual ffmpeg builds after September 18, 2020?

It's kind of strange for ffmpeg to kill off there only resp for windows builds. I'm guessing the person who did the builds has lost interesting in doing it.

You have a few options:
1. Build your own, you can also build 'non-free' version of ffmpeg. if you don't know how to build it by hand you can use automation scripts like: https://github.com/m-ab-s/media-autobuild_suite.

2. There are are many sites that release unofficial builds of ffmpeg, you can usually find them on video encoding sites and there forums like videohelp or doom9.

3. We release ffmpeg build with Staxrip(Link: https://github.com/staxrip/staxrip) using custom build It also takes up less space, Since we remove all the useless features from the build and we enable VS as well.

4. Other encoding software that uses ffmpeg will also package the tool as well you can just grab the tool and extract ffmpeg.

**Comment by cooperdk** [comment]
I have decided to built it for my project (https://github.com/cooperdk/YAPO-e-plus)... so it is freely available here:

https://porn-organizer.org/dl/ffmpeg-latest.zip

On the main website, when it's up, I'll make a page with the releases.

Current release is 4.3.1 daily (git), built with all libraries (100+ mb).

**Comment by Revan654** [comment]
> 
> 
> I have decided to built it for my project (https://github.com/cooperdk/YAPO-e-plus)... so it is freely available here:
> 
> https://porn-organizer.org/dl/ffmpeg-latest.zip
> 
> On the main website, when it's up, I'll make a page with the releases.
> 
> Current release is 4.3.1 daily (git), built with all libraries (100+ mb).
> 
> I build it for Windows x64 on Linux for stability, ffmpeg being a Linux native application.

Zeranoe was a bit overkill with all the encoders/decoders. I doubt you will ever need 80% of what is packaged into the build. Not all the encoders/decoders are free, I would make sure to make sure it's sets to one of it's licenses before releasing it. I would suggest GPL 3.0 since the others does not allow x264 and x265.

My personal build is less then 20 mb.

FYI, ffmpeg is not a Linux native application, some resp might have it preinstalled with certain builds.

**Comment by cooperdk** [comment]
WIth my software, you never know what you need so I need something that supports whatever people might have encoded with in the last 25 years.
I am aware that I probably have to adapt - my software is licensed under GPL 3.0. So there wouldn't be an issue with x26x which is what most use now. I do have to support WMV for transcoding, though.

As of now, I release it separately and the download happens later, so there are no licensing issues concerning my app, because it's not bundled with the software which is open source.

I haven't had a chance to check out if there's anything commercial in it, but I am pretty sure it is almost the same as Zeranoe's build. Anyway, since Zeranoe can release it, I believe others can, if it's not part of anything commercial.

BTW, the 20 mb must be with shared libraries. If not, it would be heavily crippled if it was to support audio as well, and that wouldn't do for a video management application.

I had luck in building VDF, by the way. I would love if it was possible to build it completely static like FFMPEG, but I guess that won't be an option.

**Comment by Revan654** [comment]
> 
> 
> WIth my software, you never know what you need so I need something that supports whatever people might have encoded with in the last 25 years.
> I am aware that I probably have to adapt - my software is licensed under GPL 3.0. So there wouldn't be an issue with x26x which is what most use now. I do have to support WMV for transcoding, though.
> 
> As of now, I release it separately and the download happens later, so there are no licensing issues concerning my app, because it's not bundled with the software which is open source.
> 
> I haven't had a chance to check out if there's anything commercial in it, but I am pretty sure it is almost the same as Zeranoe's build. Anyway, since Zeranoe can release it, I believe others can, if it's not part of anything commercial.
> 
> BTW, the 20 mb must be with shared libraries. If not, it would be heavily crippled if it was to support audio as well, and that wouldn't do for a video management application.
> 
> I had luck in building VDF, by the way. I would love if it was possible to build it completely static like FFMPEG, but I guess that won't be an option.

Actually it contains more then Zeranoe and it sits at 20 Mbs, fully static. The compiler used is different, it's faster then pre-package compiler that comes with VS2019. The difference is, the build scripts it doesn't add any source code that's not directly used within ffmpeg. Which can reduce the filesize and can speed up the performance.

It has audio encoders as well.

New lib site: https://www.gyan.dev/ffmpeg/builds/

**Comment by cooperdk** [comment]
Sounds impressive. Actually, my version is built in a similar way, and on Linux with the compilers that it was written for.
Your full build (which is currently what I provide for my script) are almost the same size as mine.
Mine is a few MB larger, that may be because it has been compiled with more libraries (probably not necessary).

This is my build's version tag:

  built with gcc 10.1.0 (GCC)
  configuration:  --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32  --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-liblensfun --enable-libvmaf --enable-libsrt --enable-libaribb24 --enable-demuxer=dash --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libaom --enable-libvpx --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-filter=frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --enable-avresample --extra-cflags='-mtune=generic' --extra-cflags=-O3 --enable-static --disable-shared --prefix=/root/ffmpeg/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --enable-nonfree --enable-libfdk-aac --enable-decklink
  libavutil      56. 58.100 / 56. 58.100
  libavcodec     58.105.100 / 58.105.100
  libavformat    58. 54.100 / 58. 54.100
  libavdevice    58. 11.101 / 58. 11.101
  libavfilter     7. 87.100 /  7. 87.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
