### ISSUE TITLE
Option to ignore symbolic links and an option to change the app's language

### ISSUE THREAD

**Issue by 1024mb** [0x90d/videoduplicatefinder#121]
**Environment**
 - OS: Windows / Any

**Describe the solution you'd like**
Currently the app resolves the symlinks and because of that it detects them as duplicates of the target file which they aren't because symlinks aren't actual files. An option to ignore symbolic links would be great to have.  
Regarding the language it would be nice if we could change it, so far I haven't seen any option to switch languages.

**Comment by Barnacules** [comment]
I was just scanning though the bugs and noticed you filed this one when I just filed a bug to allow for the creation of symbolic links when removing duplicates so they are still accessible at those locations. I think my feature request and this bug conflict with each other a little bit. But it does make sense that it should ignore symbolic links when scanning since it will always see it as a duplicate since it's literally pointing back to the original. I suspect this isn't something that is a problem in Linux hence why it's happening in this program under Windows that builds for both platforms and treats the filesystems the same. I don't even know if this program contains any NTFS specific code.

It would be neat if it understood symbolic links both when scanning and when removing duplicates with an option to create one. That would make it an insanely powerful tool for saving storage on devices with many duplicate multimedia projects or multiple installs of different applications with small changes between them. I just found out X-Plane11 literally eats up 15GB of storage just to store smaller versions of each graphic when the larger graphic could be scaled down easily and quickly at load time. It's crazy how much developers will sacrifice storage to save a little load time 😉

**Comment by 1024mb** [comment]
@Barnacules I don't think they conflict, both features are useful together. As an example take DupeGuru, they have an option to ignore symlinks and also an option to replace the files with symbolic links, even so I would have requested that if I had used the app.

**Comment by 0x90d** [comment]
Symbol links act likes files, its not an issue if they get scanned by VDF. But by adding another wish to create symbol links of all checked items, your request makes sense. It has been added in v3. Regarding the language I have no plan for adding any other than English language to v3. If people can use the internet they can speak English and this tool is not popular enough that other languages will consistently gets updated and then we have an English / translation mix which is completely nonsense.
