### ISSUE TITLE
 filename which has the double quote sign "

### ISSUE THREAD

**Issue by rezad1393** [0x90d/videoduplicatefinder#122]
**Environment**
 - OS: [e.g. Windows / Linux]
archlinux x65

scan a folder with a filename which has the double quote sign " in it.
it with give an error like:
No such file or directory

**Comment by Barnacules** [comment]
You're not allowed to place double quotes in file names under Windows? Are you scanning Linux partitions under Windows 10 where such file names could exist? I'm just curious because if I try to even create a file with a double quote it won't allow me to since the Windows 10 file system stack interprets it as encapsulation of filenames with spaces. But, if there is an edge case where a file can exist with a double quote can you even open it under Windows?

I'm not a developer on this project, just trying to gather more data on this bug since I noticed it and was curious how you ended up with a filename containing a double quote 🤔

![image](https://user-images.githubusercontent.com/8484226/104871345-abf81880-58ff-11eb-884c-e28449449639.png)

**Comment by rezad1393** [comment]
"Environment

    OS: [e.g. Windows / Linux]
    archlinux x65
"

I thought I specified my OS in the first post?

if it is not clear, here it is:
I am trying to scan a folder under linux. I don't use windows.
maybe it is because this application is dotnet based?

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
