### ISSUE TITLE
attempting to scan 20,000 images causes overflow

### ISSUE THREAD

**Issue by 0rphon** [0x90d/videoduplicatefinder#138]
**Environment**
 - Windows 10.0.19042 (Windows 10 Pro) [64-bit]
 - Video Duplicate Finder v2.0.8

**Describe the bug**
attempting to dedup 21,736 images (18.1gb) causes the program to become unresponsive for a long time (not necessarily a bug in itself considering the amount of files) and then when it finally finishes and attempts to display the results it causes the following error

![image](https://user-images.githubusercontent.com/59403052/121682251-b2cf2580-ca70-11eb-969d-3229ad08f5ec.png)

**Comment by Maltragor** [comment]
I would expect that there are at least two (as similar classified) images in your collection that are not proper handled by the GetImageThumbnail() function.
The number of images should not be the problem.
GetImageThumbnail() calculate the thumbnail size and calls the Graphics.DrawImage() function to get the resized image.
Graphics.DrawImage() recognizes that something got wrong by calling CheckErrorStatus() and throws the exception which is not handled by VideoDuplicateFinder.

First I thought it happens if the aspect ratio of a image is very different, because GetImageThumbnail() calculates a width or high of 0 in this case. This also leads to an (different) unhandled exception but happens one line before when the internal bitmap is created.

If you like to modify the code and rebuild it, you could catch the exception and generate a log entry instead.
There is already a `try { ... } catch (Exception ex)  { ... }` statement within GetImageThumbnail(), but only for `bitmapImage = Image.FromFile(videoFile.Path);`
So `} catch (Exception ex)  { ... }` needs to be moved to the end of the loop.

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
