### ISSUE TITLE
Opening all files in a group at once.

### ISSUE THREAD

**Issue by M7mDKFM** [0x90d/videoduplicatefinder#139]
- OS: Windows

I often find myself opening every video in a group to visually compare their differences, so it would be really nice if there was a way to open all the files in a group at once, such as with Shift + arrows to select multiple files then pressing Enter to open them all at once.

**Comment by Maltragor** [comment]
I have also thought about the possibility of opening a whole group (or parts of it).
So for example that a double click on the group header/row opens all elements of the group. Or via right click on the group row -> (group specific) context menu -> open all.
Or (additive) via a multiselect of several lines,...

Open/Item actions in general:
(In file manager, in application, open multiple files, send to, "custom action",.... )
A configurability of existing actions and the possibility to add new custom actions would be quite interesting.

About configurability: 
So the possibility to define the command line operation itself. Or if you want to do without the configuration aspect within VDF, that you can store a shellscript for each (open) action. VDF checks before the action then whether such a script file is in the directory, if yes, this is executed, if no, then the previous default action.

To extensibility:
Especially for multiselect and for actions that work on entries selected by checkboxes.
With own actions you could build your individual file delete/link actions per script, export scripts for different formats, realize a synchronization of the players when comparing several videos, etc.

Let's go back to the concrete example of opening a whole group:
For example, you can use the mpv player to play multiple videos synchronously:
`mpv --lavfi-complex="[vid1][vid2]hstack[vo];[aid1][aid2]amix[ao]" input1.mkv --external-file=input2.mkv`
Or something like https://gitlab.gnome.org/YaLTeR/identity/

**Comment by 0x90d** [comment]
Instead of opening the videos and play them a better solution is to let ffmpeg create bigger thumbnails, then show them in a new window. I think @M7mDKFM only wants to see if one video has a watermark or logo or minor differences you cannot see on the tiny thumbnails (and mouse hover only enlarges the tiny thumbnail).

Another workaround would be changing the mouse hover behavior to generate a high resolution thumbnail instead of enlarging the current thumbnail.

**Comment by gtTracy** [comment]
For what it's worth, I can see the usefulness of having the higher resolution thumbnails, but since it may not be something everyone wants to have, perhaps having an option on the Settings tab - something along the lines of "Create higher resolution thumbnails". I was originally thinking that it might be useful to have that as a separate background process, but upon rethinking, I suspect that would be too much of a performance hit, since the files would have to be loaded from disk a second time - probably easier to just save them during initial processing if the option to create them is set.

**Comment by M7mDKFM** [comment]
No, it is pretty much just as I said, so let me clarify. I usually double click each video from a group to open them on top of each other as a means of **preview.** I want to see the videos playing simultaneously so I can tell what's different between them, as the nature of the videos i'm comparing have slight differences that I can't tell from thumbnails only. Of course, I know asking for video preview for multiple files is a high stretch, and is a huge unnecessary bloat on the program. That's why in my ticket I asked if it's possible to add a function where you can select multiple files from the results and press Enter or whatever to open them at the same time, similar to what would happen if you selected multiple video files in Windows File Explorer and pressed Enter.

**Comment by Maltragor** [comment]
I made a PR: #248 
It allows to define custom commands for open actions with single and multi selection (for normal open and open in folder).
In addition if the multi open actions are defined, a corresponding open menu item for groups gets visible.
Selected Items can be opened be pressing enter. Depending on the focused column the corresponding open command is called (normal / in folder).
