### ISSUE TITLE
Linux Binary 2.0.8 not starting: No precompiled XAML found

### ISSUE THREAD

**Issue by Sha1rath** [0x90d/videoduplicatefinder#150]
Hi,

I was trying to run the latest binary release on Arch Linux. I have ffmpeg, ffprobe and libgdiplus installed.
When trying to run VDF, I get this error:

```[rawjaw@ws2 VDF.Linux-x64]$ ./VideoDuplicateFinderLinux
Unhandled exception. Avalonia.Markup.Xaml.XamlLoadException: No precompiled XAML found for VideoDuplicateFinderLinux.App, make sure to specify x:Class and include your XAML file as AvaloniaResource
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj)
   at VideoDuplicateFinderLinux.App.Initialize() in C:\Users\User\Desktop\DuplicateFinder\VideoDuplicateFinderLinux\App.xaml.cs:line 11
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at VideoDuplicateFinderLinux.Program.Main(String[] args) in C:\Users\User\Desktop\DuplicateFinder\VideoDuplicateFinderLinux\Program.cs:line 7
Abgebrochen (Speicherabzug geschrieben)
```

**Comment by 0x90d** [comment]
I'm sorry but v2 is deprecated. I recommend you build either v3 (master) or wait until it's "stable" enough for me to publish binaries.  Or you buid v2 (see readme) and see if it works.

**Comment by guihkx** [comment]
The 2.0.8 version is pretty messy and has a lot of bugs. The new 3.0 version is much better, though I don't understand why there's no binary release of it yet.

Also I'm not a .NET expert, but I found it a bit awkward to compile it right now (at least on Linux), so here are the commands I used to get a working build:

1. Create a temporary directory that will be used to download the .NET 6 SDK:

    ```
    mkdir -p ~/dotnet6
    ```
2. `cd` into the SDK directory:

    ```
    cd ~/dotnet6
    ```
3. Download a daily build of the .NET 6 SDK:

    ```
    curl -LO https://aka.ms/dotnet/6.0/daily/dotnet-sdk-linux-x64.tar.gz
    ```
4. Extract the SDK:

    ```
    tar xzvf dotnet-sdk-linux-x64.tar.gz
    ```
5. Export the `DOTNET_ROOT` environment variable, pointing to the SDK directory so that the compiler knows where all the files are:

    ```
    export DOTNET_ROOT=$HOME/dotnet6
    ```

Now we're going to actually compile VideoDuplicateFinder:

1. Let's clone the VDF repository to `~/videoduplicatefinder`:

    ```
    git clone https://github.com/0x90d/videoduplicatefinder.git ~/videoduplicatefinder
    ```

2. `cd` into it:

    ```
    cd ~/videoduplicatefinder
    ```

3. As of today, VDF can only compile with a nightly build of the .NET 6 SDK, so we also need to create a file named `NuGet.config` inside VDF's directory, with the following content:

    ```xml
    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
        <packageSources>
            <clear />
            <add key="aspnetcore" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" />
            <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
        </packageSources>
    </configuration>
    ```

4. Now we can actually compile VDF:

    ```
    ~/dotnet6/dotnet publish -r linux-x64 -c Release --self-contained -o VDF.Linux-x64
    ```

5. If everything went accordingly, VDF will be sitting under the `~/videoduplicatefinder/VDF.Linux-x64/` directory, and you can move the whole directory somewhere else and then delete both `~/dotnet6` and `~/videoduplicatefinder/` to free some space.

**Comment by guihkx** [comment]
Looking and working good so far!

![Screenshot from 2021-08-09 23-12-15](https://user-images.githubusercontent.com/626206/128797993-6d6e6ee4-e1a1-4b3b-b91a-15cd76fc6ab5.png)

**Comment by Sha1rath** [comment]
@guihkx Thank you very much for these instructions, this is what should be in the README. As somebody with zero experience with dotnet on Linux, I didn't have any Idea what to do with the sources.
With your help I got the recent build to run but it always crashes when the scan is finished. As this is a development version, I won't bother opening more issues. I'll stick to using 2.0.8 with wine (yeah, that works) until there is a newer release that is considered stable.
