### ISSUE TITLE
3.0.x spawns infinite number of ffmpeg subprocesses, eating all system resources

### ISSUE THREAD

**Issue by CrendKing** [0x90d/videoduplicatefinder#163]
**Environment**
 - OS: Windows

**Describe the bug**
It seems there is no limit of how many ffmpeg subprocesses can spawn simultaneously when the scan starts. If scanned directory has large number of videos, these subprocesses quickly drains memory and eats all CPU and GPU resources. Worse, since the system is frozen, there is no way to stop them.

**Expected behavior**
There should be limited number of parallelism, e.g. maximum of the number of logical cores of ffmpeg subprocesses.

I tried to add a small `ParallelOptions.MaxDegreeOfParallelism` to https://github.com/0x90d/videoduplicatefinder/blob/fd02535069c4ddea96a56d18e4c670fcc4e493fa/VDF.Core/ScanEngine.cs#L302. The symptom lessens, but not completely gone. Large number of ffmpeg can still coexist. VDF doesn't wait for process 1 to finish before spawning process 2, etc.

**Comment by Maltragor** [comment]
To be sure:
There are two functions / two scan phases calling ffmpeg.
One is the RetrieveThumbnails(), the other is GatherInfos() -> GetGrayBytesFromVideo().

The question I had also asked myself was, according to which rules the degree of parallelization is determined by .NET at all in e.g. Parallel.For. Because much does not always help much^^.
And the number itself is generally also not a sufficient criterion.
(So is more just a general question, but had fit in the context here)

Could it make sense/help to run ffmpeg with reduced priority in relation to VDF?

**Comment by CrendKing** [comment]
You are right. If I add `MaxDegreeOfParallelism` to GatherInfos(), the subprocess number is limited as expected. There's also a Parallel in ScanForDuplicates(). After adding to all 3 parallels, VDF is usable now.

So maybe consider adding it to a setting?

**Comment by yami-no-tusbas** [comment]
Anyone as a patched version ?

**Comment by anaisbetts** [comment]
Max Parallelism should never be -1, it should always be constrained here.
