### ISSUE TITLE
MacOS claims ffmpeg is not signed

### ISSUE THREAD

**Issue by speedheathenULTRA** [0x90d/videoduplicatefinder#168]
@0x90d I was able to get the application to finally load after setting my default shell back to ZSH and performing the CHMOD 755 on VDF.GUI.

The issue now is that when I select GPU Accelerated mode it does scan all the files and very fast but produces no thumbnails. If I try to uncheck that box when I click scan it brings my insanely powerful 24-core machine to a grinding hault.

Any thoughts?

**Comment by 0x90d** [comment]
I'm not taking any money. This is a free project and I'm doing this in my free time. Have you seen this here? https://github.com/0x90d/videoduplicatefinder#macos-user works fine on my end. I can launch the app on MacOS without any issues. MacOS only claims that ffmpeg is not signed and therefore not allowed to launch. I don't know how to sign apps on MacOS. That's something you have to figure out yourself. I will leave this issue open in case someone knows the solution. The only rule is that nobody advertises his project and no business deals will be discussed. Otherwise I will close this immediately. This is not the place for getting jobs or doing advertisment.

**Comment by speedheathenULTRA** [comment]
@0x90d I will gladly donate to the project, but it just doesn't make sense if I can't use it. Does that make sense to you? Do you know of anyone else using it successfully on MacOS aside from yourself?

**Comment by speedheathenULTRA** [comment]
One thought, I can't seem to get apt-get to install? I use Homebrew for packages.

**Comment by 0x90d** [comment]
@speedheathenULTRA Did you not read what I said? I will NOT take any money. You can download macos ffmpeg binaries right from the download page. You may need to run chmod 755 on VDF and ffmpeg to set execute rights. Please use edit function and do not create double posts thank you.
