### ISSUE TITLE
Still crashing on GetGrayBytesFromVideo

### ISSUE THREAD

**Issue by floydcg** [0x90d/videoduplicatefinder#170]
**Environment**
 - OS: [e.g. Windows / Linux] Windows or Linux

**Describe the bug**
Latest build from the latest commit. 
Still crashing once a database is built from an initial scan. Subsequent Scans will scan 1 file and crash. V2 scanned the same files without issue.   Latest FFMPEG binaries. NOT a database from V2. its a fresh database from V3, Delete database and rescan, no crash. change % of match and scan again, crash. leave % alone and scan again, crash. Again, every build i've tried, i've deleted everything and started from scratch.  Same error every time, and the same error that's been referenced and closed as fixed several times: 

Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
---> System.NullReferenceException: Object reference not set to an instance of an object.
at VDF.Core.FFTools.FfmpegEngine.GetGrayBytesFromVideo(FileEntry videoFile, List1 positions) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\FFTools\FfmpegEngine.cs:line 67 at VDF.Core.ScanEngine.<GatherInfos>b__50_0(FileEntry entry) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\ScanEngine.cs:line 199 at System.Threading.Tasks.Parallel.<>c__DisplayClass44_02.b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x103
--- End of stack trace from previous location ---
^
this error repeats depending on how many threads are allowed.

**Comment by 0x90d** [comment]
I cannot reproduce this. Can you share an example video for me where this happens?

**Comment by Maltragor** [comment]
OK, I will try it again...

pleas read everything and ask if I have not expressed something understandably.
(Short: a) It is the old bug, @floydcg does not seem to have updated after all. b) But @0x90d "fixed" the bug but has not yet completely understood bug.) 

a) Reading the trace from @floydcg:
GetGrayBytesFromVideo -> FfmpegEngine.cs:line 67 -> ScanEngine -> ScanEngine.cs:line 199
Since commit "_Fix NRE for people upgrading from an older version_ #160" 16a84c3df04901ce6adee785ee41143f5abd7938  (2021-08-17) GetGrayBytesFromVideo is no longer in line 199.
So either it is a old trace log or VDF was not build from the latest commit.

b) In  "_Latest build crashes and exits without any error codes or messages_ #154" I had explained what happens, see "Main Bug:" and the comments after the bug was closed.
The deserialisation of the database file loads an empty dictionary as `null`. No Version incompatibility between database files. It happens every time.
You can try it:
- Create a empty (text)file and name it "crash.mp4". 
- Delete the database file
- Run VDF and add the folder of this file to include list
- Start a search -> Nothing bad will happen
- Start the search again -> the database is reloaded, grayBytes is null
- The fileEntry is still flagged with ThumbnailError. InvalidEntry() does not filter the entry, so GetGrayBytesFromVideo is called. (May be correct, I don't know if the flagged file should be tried to load each time)

The Bugfix commented with _"This is for people upgrading from an older VDF version"_ assigns a new empty dictionary and so VFD won't crash, but as the comment says, there was obviously not the knowledge about the much bigger problem than loading an old database version.
(In addition to this case with grayBytes also consider that other future empty elements in `FileEntry` could be affected. _Maybe there is a serialisation/deserialisation option how to handle empty containers? Don't know_)

**Comment by bobsage123** [comment]
I am on the latest commit as of posting this and am also getting crashes with a clean install of VDF either during the enumeration process or after it finishes (I haven't caught exactly when the app crashes). But it leaves no error.

**Comment by Maltragor** [comment]
> But it leaves no error.

Even if you start it from console window?

> This happened in 2.0 VDH

Not sure if I understand you correctly. Du you mean that if VDF 2 crashed in past you could fix it by deleting the database and in V3 you also tired it after a crash but you didn't found any .db file?
If you don't find the .db file in the directory of V3 I would assume that VFD crashes before it is created.

**Comment by bobsage123** [comment]
> > But it leaves no error.
> 
> Even if you start it from console window?
> 
> > This happened in 2.0 VDH
> 
> Not sure if I understand you correctly. Du you mean that if VDF 2 crashed in past you could fix it by deleting the database and in V3 you also tired it after a crash but you didn't found any .db file?
> If you don't find the .db file in the directory of V3 I would assume that VFD crashes before it is created.

I always start it from the .exe. Didn't know there was another option.

You are correct. So it is probably crashing during the enumerate section.

If there is a crash\error log file I can look at I can paste it here.

**Comment by Maltragor** [comment]
@floydcg

While building the windows version in order to answer @bobsage123 I noticed that on https://github.com/0x90d/videoduplicatefinder/releases/tag/3.0.x only the executables are updated daily. So If you downloaded the source as zip file form the release page you got not the current version. In the zipped Version `GetGrayBytesFromVideo` is called in line 199 and the program will still crash.
So if you build the application yourself you should download the source directly from the master branch in order to realy get the latest version.

**Comment by Maltragor** [comment]
@bobsage123 

On Linux the exceptions are logged to the console window and I never tested the behavior under windows. So my expectation was that is the same there. But it isn't. So executing it in console window would not help.

But I can tell you at least one way to get the informations about the crash:
Open the Start Menu, search for "Event" => Run "Event Viewer"
Go to "Windows logs" ->  "Application"
After e.g. VDF crashed by an unhandled exception you will find an entry of source ".NET Runtime" with a error log like this:

> Application: VDF.GUI.exe
> CoreCLR Version: 6.0.21.37719
> .NET Version: 6.0.0-preview.7.21377.19
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.AggregateException: 
> ...

This (complete) log includes information about where the exception occurred.

**Comment by bobsage123** [comment]
> @floydcg
> 
> While building the windows version in order to answer @bobsage123 I noticed that on https://github.com/0x90d/videoduplicatefinder/releases/tag/3.0.x only the executables are updated daily. So If you downloaded the source as zip file form the release page you got not the current version. In the zipped Version `GetGrayBytesFromVideo` is called in line 199 and the program will still crash.
> So if you build the application yourself you should download the source directly from the master branch in order to realy get the latest version.

Seems like @0x90d should be made aware of this if not already. I'm not familiar with building it so hopefully 0x can fix the release.

Thanks for your help in troubleshooting.

I will wait till I get the correct full newest release before checking any logs. Maybe it will fix the issue.

**Comment by bobsage123** [comment]
@Maltragor I checked the log and it was crashing on one folder with a corrupt filename that was inaccessible. I managed to delete the folder and rerunning now. Fingers crossed.

**Comment by bobsage123** [comment]
So the entire scan completed. Afterwhich it showed zero results (I know there are duplicates from running 2.0 from beforehand).

I checked the log and there was a bunch of graybytes errors followed by this. It says "Scanning for duplicates in 0 files"?

![image](https://user-images.githubusercontent.com/20603861/130338917-9ae132c6-3c6f-4bb0-a72b-cceb547e317f.png)

**Comment by Maltragor** [comment]
@bobsage123 
> Seems like @0x90d should be made aware of this if not already. I'm not familiar with building it so hopefully 0x can fix the release.

I think there was a misunderstanding:
The prebuild zip files: App-win-x64.zip,... are based on the latest version. (e.g. see the date of the exe file. And the version also no longer crashes during my test with the empty crash.mp4.). But only the zipped source code below is older.

_At that time I build build VDF from source in order to add some code that will crash it because my goal was to see the behaviour in this case to give an answer how to get more informations about the crash. And as I was already on the release page at that point I decided to do it that way and downloaded the source from this place. And while adding the crashing code I noticed that this is not the latest code version. As maybe @floydcg also downloaded the source from the release page and built it himself, I mentioned it._

**Comment by bobsage123** [comment]
Ah okay understood. But I guess that still leaves me with my problem. I am able to fully complete the scan without any crashes, but I am left with zero results, despite knowing I have duplicates.

**Comment by Maltragor** [comment]
As you might imagine, based on your description so far, it's hard to guess what exactly is causing this.

If the "Enable GPU Acceleration" option is active, I would recommend disabling it as a test.

Also, I would suggest that you create a directory for testing and put two copies of the same video in there.
E.g. https://filesamples.com/samples/video/mp4/sample_1280x720.mp4
Then we have a simple setting from which we know that under normal conditions VDF definitely will identify this as duplicates.
If there still will be be "graybytes errors" logged while "GPU Acceleration" is disabled you would take a closer look at what ffmpeg outputs....  But then this should be done in an new issue. When I answered on this already closed one my intention only was to tell how to get the crash report and tell floydcg the other thing I wrote. In addition as VDF does not crash when calling GetGrayBytesFromVideo it does no longer fits to the topic.

**Comment by bobsage123** [comment]
Understood, thanks for your assistance. I will try this and open another topic if I need further support.

Another thing I noticed was even though I put new ffmpeg\ffprobe files in my VDF directory, my PATH variable was pointing to a very old version. So maybe VDF was using this and causing problems. Going to replace there as well.
