### ISSUE TITLE
setting xml file do not update unless normal program end

### ISSUE THREAD

**Issue by wowkkwow** [0x90d/videoduplicatefinder#186]
**Environment**
 - OS: windows 10 pro 21H1 19043.1165

**Describe the bug**
I downloaded latest windows version (Daily build v3 (unstable)) and used. 

But had a simple bug with automatic save settings.

After setting and clicking the start button, 'Settings.xml' is not made(if it's the first setting) or refreshed.

(I have run the VDF  as administrator, but also same)

So after sudden program end because of crash or something, I have to set the all previous settings.

Now I am doing  normal end and restart VDF before start scanning.

In addition, list checking with space bar key does not work, but unchecking works

And Chinese, Korean, Japanese letter are broken in renaming window.

![image](https://user-images.githubusercontent.com/43441443/131813521-b390f027-1aed-4742-97a6-bf0c97fb1a8b.png)

It do not update the new name in the result list, too.

**Expected behavior**

I hope 'Settings.xml' file's saving or refreshing are made in real-time. 

So the latest setting preserved after a sudden program end.

And list checking with space bar key would work, unbroken letter in renaming window and updating new name in the result list.

Thanks for reading.

**Comment by Maltragor** [comment]
As there are four different issues I divide them a little further:

(1) Settings.xml - time of saving 
Based on the current implementation the XML is only saved when main window is closed properly. 
So if this does not happen e.g. because of an crash the changes are lost.
-> Category feature request: Keep settings or allow to restore them if VDF crashes.

(2) No (view) update after renaming
This was also a comment in my pull request #183 where I added/integrated the InputBox in the place where renaming was prepared. (Because I don't know how to fix it)
> The renaming works, the model/ItemInfo is also updated but the view keeps the old filename. So ChangePath() -> OnPropertyChanged() seem not to have the effect of updating the view.

(3) Chinese font
This seems to be a bug of avalonia, the UI framework used for VDF.
https://github.com/AvaloniaUI/Avalonia/issues?q=+TextBox+chinese+

(4) List checking with space bar
Does checking really never work? 
When I (Linux) first click on a check box and then press space multiple times, the checkbox toggles as expected.
What does not work is to select a row and then use space to toggle the checkbox. Because selecting a duplicate row does not give the checkbox the input focus.
By clicking with the mouse on the checkbox, i.e. the first checking, the checkbox receives the focus so that it can be toggled using space. 
So probably we talk abut the new feature that the checkbox of the selected row should toggle by pressing space.
(One solution would be my PR #187)

**Comment by wowkkwow** [comment]
![Animation](https://user-images.githubusercontent.com/43441443/131986537-20f6df86-f422-48a2-ab66-dc06deedcd57.gif)

The checking works by space bar only in smallest checkbox.
