### ISSUE TITLE
Set Rules for Automatic Deletion Logic

### ISSUE THREAD

**Issue by winb1g** [0x90d/videoduplicatefinder#190]
**Environment**
 - OS: Any

**Describe the solution you'd like**
Post-scan, VDF provides information of the video such as bitrate, resolution, path (for subdirectories), etc. Automatic Deletion Logic means to me that the user would be able to not only be able to scan for duplicate videos/images in batches, but also remove those duplicates that are unwanted in batches.

**Sample Criteria** 
- Either Pre- or Post-scan, the user would be able to optionally set rules for which files they would like to have automatically deleted by choosing the path, smaller/larger size, smaller/larger resolution, smaller/larger bitrate, etc.
- Additionally, there may be cases where there is not a 100% match, we could use a boolean to determine whether the user wants to also remove those that may not be 100% matches but is safer to only assume this happens for 100% matches.

**Comment by 0x90d** [comment]
I'm against any kind of auto deletion. If something doesn't work as expected then people will be frustrated and tell its my fault that they lost specific media files. The responsibility must remain with the user.

However there can be rules to pre-check files based on the criteria in your post. User still has to validate and hit the delete button himself. 

If that is not what you want, then you have to export the results and write a script that parses it and auto delete the files.

**Comment by gtTracy** [comment]
I know this is a late response here, but I agree with not putting any type of autodelete in. It causes too many problems (and too many bug reports about how "the program ate all my files").

I am not sure about pre and post checks for files. I would assume post checks would be using the Selection option on the Scanner tab, with either pre-defined options or Select Custom to build a custom check. If that is correct, then I would like to add a suggestion of being able to save (with a user definable name) and load strings here - so that a user could, for example, use Select Custom to build a selection string of "(arg.ItemInfo.IsBestFrameRate && arg.ItemInfo.IsBestDuration)" and be able to save that as, for example, "Select Best Size And Length" and be able to load that each time the program loads, so that it appears as a selectable option (without having to do Select Custom again and recreate the selected options).

**Comment by 0x90d** [comment]
> then I would like to add a suggestion of being able to save (with a user definable name) and load strings here

This is exactly what I was thinking about

**Comment by winb1g** [comment]
> 
> 
> I know this is a late response here, but I agree with not putting any type of autodelete in. It causes too many problems (and too many bug reports about how "the program ate all my files").
> 
> I am not sure about pre and post checks for files. I would assume post checks would be using the Selection option on the Scanner tab, with either pre-defined options or Select Custom to build a custom check. If that is correct, then I would like to add a suggestion of being able to save (with a user definable name) and load strings here - so that a user could, for example, use Select Custom to build a selection string of "(arg.ItemInfo.IsBestFrameRate && arg.ItemInfo.IsBestDuration)" and be able to save that as, for example, "Select Best Size And Length" and be able to load that each time the program loads, so that it appears as a selectable option (without having to do Select Custom again and recreate the selected options).

Agree that this is a better solution
