### ISSUE TITLE
Recently changed MessageBox size and usage

### ISSUE THREAD

**Issue by Maltragor** [0x90d/videoduplicatefinder#212]
**Environment**
 - OS: Linux

**Describe the bug**
- The MessageBox height is always very large
![grafik](https://user-images.githubusercontent.com/36803696/134784537-d490392d-9733-463c-a25e-1886e730b28f.png)
(Only one example)

- When the MessageBox is used to show an exception the text may be so large that only parts of the text and no buttons are visible
![grafik](https://user-images.githubusercontent.com/36803696/134784612-9135e649-affc-436b-96f2-1d56aad83c5d.png)
Maybe only show the exception name / short exception info and point to the log for more details?

**Comment by 0x90d** [comment]
This is because of https://github.com/0x90d/videoduplicatefinder/commit/60fc6ad124aa894686c4f9265434c202bc183eb0 when I remove the changes the messagebox is fine on Linux but broken on Windows. With this change, its fine on Windows (at least sort of) but broken on Linux. Its an Avalonia bug.

One solution might be removing it from XAML and adding this in code if it runs on Windows.
