### ISSUE TITLE
Rename file - Exclude file extension from Prompt?

### ISSUE THREAD

**Issue by BlokeCDP** [0x90d/videoduplicatefinder#229]
**Environment**
Windows

**Describe the solution you'd like**
Do not show the File Extension in the prompt when renaming the file - when selecting the text you can not simply select all text and then start typing, you have to unselect the file extension - not sure what the relevance of having the file extension in the prompt is. Other potential solution is to highlight the text in the prompt but do not highlight the file extension

V2 does not show the extension so not sure if this is a bug or is expected behaviour.

(Many thanks for the tool by the way, it is awesome).

**Comment by Maltragor** [comment]
When I added the InputBox in #183, having also the file extension in the prompt was intended.
For me, the extension belongs to the file name. One of the first things in a new Windows installation for me is to reconfigure the Explorer so that the file extensions are displayed :-)

At that time there was no auto selection at all. Because most of the time I only partial modify the name or add something, auto selection was also not relevant to me.

In #230 now I have added a selection start and end parameter and used it to keep the extension not selected/highlighted.
At least that was the intention. Under (my) Linux (Mint) neither the old variant with SelectAll() nor my change had worked. Without Focus() at least the selection is set correctly. But the Focus() call makes any selection disappear again.
