### ISSUE TITLE
Select Custom: Last Group is skipped during selection

### ISSUE THREAD

**Issue by scrapix** [0x90d/videoduplicatefinder#232]
**Environment**
 - OS: Windows 

**Describe the bug**
When selecting videos in bulk through "Selection>Select Custom..."
And using expression: "arg.ItemInfo.Path.Contains("{anyString}")"
Almost all videos in every group are being selected correctly **EXCEPT in the last group**. 
The last group seems to be skipped during the selection.  (Maybe the loop finishes to early?)

**Expected behavior**
Every group will be checked for the selection condition / expression

![grafik](https://user-images.githubusercontent.com/23144020/137465422-a9cdf23a-519a-481c-93d6-9650b816184e.png)

**Comment by Maltragor** [comment]
It would be interesting to discuss how the "Select Custom..." works or should work at all.

Because yes, related to the loops in the function no element is forgotten, but I have the impression that overall not necessarily what one would expect is checked.

Some things I noticed - if I understand the procedure correctly:
- There is a mechanism to skip already processed groups (`blackListGroupID`) but the selection process itself is not limited to the group of element `first` but selects all matching duplicate items.
- The currently processed element `first` on the one hand is exclude by the additional condition of `ParseAsDelegate` and on the other hand it is always unchecked at the end of the loop.

So in the example of 0x90d:
- In the first loop every item expect "...Duplicates/toys-3.." (the first item in the list) is checked and at the end this element again is unchecked.
- second and third loop are skipped because of the already processed GroupID
- "..."Duplicates/sample-mp4-..." (the first item of the second group) is `first`. All other items are checked (so "...Duplicates/toys-3.." gets also checked)

Example of scrapix:
=> Note: here the first item of the last group matches the path condition but not the second one!
- So in the first loop all "~OldUnsortedPhotos" are checked expect the first one in the list.
- In each following loop the previously unchecked item is checked and the first one of the currently processed group is unchecked
- And at the end the first one of the last group is the unchecked one. But as this is the only one matching the condition, no item is checked at all.


So in my opinion the "Select Custom..." algorithm should be changed:
-> Only select items of the group of element `first` and ignore the elements of the other groups
-> Not always uncheck or ignore the first element. Check all matching elements and only if each element of a group would be  checked make a special treatment. As there is nor rule which element should be unchecked maybe uncheck the first one or maybe uncheck all elements because of the missing rule so the user has to decide.
