### ISSUE TITLE
Bug - Program crash when scanning files using ffmpeg native binding

### ISSUE THREAD

**Issue by gtTracy** [0x90d/videoduplicatefinder#235]
**Environment**
 - OS: [e.g. Windows / Linux]

Ubuntu 20.04.3
ffmpeg version 4.2.4-1ubuntu0.1
VDF 3, daily build dated 2021-10-16

**Describe the bug**

When scanning files, using ffmpeg native bindings, the program aborts (GUI completely closes), with error:

`
[matroska,webm @ 0x7f0400a059c0] Could not find codec parameters for stream 0 (Video: h264, none, 406x720): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Assertion desc failed at src/libswscale/swscale_internal.h:670
Aborted (core dumped)
`

**Expected behavior**

Needed: a way to list the file(s) that is causing the error. My guess is that one of the files has a corrupted header, or some other type of file corruption. But I don't have a way to isolate which file it is.

**Comment by gtTracy** [comment]
I don't suppose that the AVPixFmtDescriptor structure has a field that contains the file name that is currently being worked on? Or perhaps a pointer to a structure that does? Because if that's in there, it would seem a simple matter to add that string to the av_assert0 code to dump it out to the log (or console, wherever that assert string is going).... Having the name of the file that failed would at least get me closer to finding out why it failed (whether the file format is invalid, or there is corruption in the file structures, etc).

**Comment by Maltragor** [comment]
All code sections of my last post are part of the external ffmpeg library.

And since ffmpeg uses an assert to ensure to get an valid AVPixFmtDescriptor this means the caller (so VDF) has to ensure that this condition must not happen.
_(And trying to patch ffmpeg to get the file name would not be useful.)_

The intension of my post was to help 0x90d to find the place an reason for the crash and to possibly also provide a solution for it.

@gtTracy To find the file without any patches you can e.g. use the linux strace command to monitor the opened files. The last one before VDF is terminated should be the one that causes the problem.
But you have to set the "Max Degree Of Parallelism" to 1 in the VDF settings tab!

> strace -f -e openat VDF.GUI 2>&1 | grep _filterstring_

Where _filterstring_ is a part of your video folder path or the file extension.
Since VDF will open a lot of other files without grep you would have to redirect the output to a file and search afterwards.
E.g.:
> strace -f -e openat VDF.GUI 2>&1 | grep myVideoPath
> strace -f -e openat VDF.GUI 2>&1 | grep -E "myVideoPath|myOtherVideoPath|moreVideos"
> strace -f -e openat VDF.GUI 2>&1 | grep -E "\.mp4|\.avi"

_If "Thumbnails" setting is larger one, each file is opened once per thumbnail._

**Comment by gtTracy** [comment]
Thanks. I'll give strace a look and see if I can find out anything. I did already find a couple of invalid files (files that were named as video files, but the actual contents of the file was plain text). So perhaps it was one of those.

**Comment by gtTracy** [comment]
I found 5 files that were causing problems, based on them being the ones that caused the program to crash (thanks again for the strace pointer). Of these 5 files, they all "play" in both totem and mvp, but they don't give any video (completely blank screen). I tried one (at random) with ffplay, and it didn't crash or drop out with an error (I don't know much about ffplay, so I don't know what it was supposed to do, but it did show a series of changing numbers across the bottom of the terminal window). If you can give me directions on what kind of information will help, I would be happy to experiment. Or, alternatively, I could send you one of the files (which, I believe, were all downloaded from YouTube).
