### ISSUE TITLE
(select lowest duration) selects GIFs instead of JPGs 

### ISSUE THREAD

**Issue by ahmedmohamedfci** [0x90d/videoduplicatefinder#238]
**Environment**
 - OS: [Windows ]

**Describe the bug**
have the app scan a folder with 2 identical files, one a GIF and one a JPG, press selection and choose (select lowest duration), the app selects the GIF.

**Expected behavior**
select lowest duration should select the JPG as the duration of a GIF is larger than a JPG even if it was 1 millisecond long.

**Comment by 0x90d** [comment]
Lowest duration is also lowest quality. If the quality of both items are identical, it selects all but the first one. This is what happens here. The duration of images is not taken into account. So this one is not a bug.

And I'm not sure if it makes sense to change the behavior. Which quality is better: GIF or JPG? Gif because its animated? Jpg because its more portable? I think it falls into the case where the user has to make his own decision and correct the selection himself.
