### ISSUE TITLE
Question about video selection and rejection

### ISSUE THREAD

**Issue by gtTracy** [0x90d/videoduplicatefinder#246]
Environment:
       Ubuntu 20.04 (although this applies to most any environment)

Question:
      Can you describe what conditions would cause a video to be accepted for scanning vs. what conditions would cause a video to be rejected / ignored by the scanning process?

For clarification, in this context, "scanning" means what happens when you start the program with no ScannedFiles.db, from "Settings" add at least one folder, then from the main screen click "Start".

Obviously an empty video would not be scanned (barring the condition in [#242](https://github.com/0x90d/videoduplicatefinder/issues/242) of course). 

Also a "video" that contains no video (such as "myvid.mp4" that contains nothing but text) would be rejected during scanning.

But what other kinds of conditions are checked? 

The prompt behind this question is that I have a drive (1.8tb) that has 100k+ video files on it, but when scanning there are files which are not picked up by the program. I know this because I was recently manually sorting files into folders (based on content), and I came across several duplicate files (files with the same name, and "visually identical" content). However, I had previously scanned these folders using VDF, and these videos did not come up as matching (even when the percent match was as low as 95 - which should definitely have caught these files).

So, I'm trying to determine what criteria they may be failing when the program scans files looking for duplicates, so that I can run a bash script to identify files that might fail to be included by VDF, so that I can ether "fix" the files so they can be scanned, or so that I can manually look for duplicated files among these rejected files.

**Comment by 0x90d** [comment]
- ffprobe fails or returns invalid content
- ffmpeg fails
- thumbnail is too dark

Best way to determine is to copy the files you know VDF has skipped into a new folder. Then run VDF on this folder only with really low settings. If VDF still has not picked those up, see what the log says. Usually in all of above there should be an entry written to the log.

**Comment by Maltragor** [comment]
My approach here to find all skipped files (by using scripts) would be first to distinguish:
a) Did VDF process the video at all
b) Did problems occur
c) Were supposedly similar videos not recognized as similar

For (a) and (b):
You can run a scan with VDF and export the database to Json (-> Database -> Export to Json)
There will be an entry fore each processed file.
```
[
    {
        "Path": ... ,
        "Flags": ... ,
        ...
    },
    {...},
    ...
]
```
So it would be possible to write a script that matches the directory structure with the `Path` entries of the json file.
-> (a) You know which files have been completely skipped
(Besides the reasons that ffmpeg cannot handle the file, another exclusion criterion is the file extension. VDF decides if it is a video or an image based on an internal list of extensions.

https://github.com/0x90d/videoduplicatefinder/blob/29d57c7734db7dabb9455ab022b1191e9ab5b352/VDF.Core/Utils/FileUtils.cs#L22-L47


For (b) you would consider `Flags` - The integer value iresults from a binary OR of the following flags:
https://github.com/0x90d/videoduplicatefinder/blob/29d57c7734db7dabb9455ab022b1191e9ab5b352/VDF.Core/EntryFlags.cs#L22-L30
So if one of the error flags is set, the file will be ignored during duplicate search.

The (c) category is unfortunately not so "easy" (in the sense of automatable) to find out. - Since this is the reason why you use a tool like VDF.
Apart from the theoretical possibility of performing a comparison search with another program, I also only see the possibility of taking a closer look at specific examples of manually found duplicates and copying them to a separate directory in order to be able to test them specifically with VDF.

I know, strictly speaking, my approach does not correspond to the requirement you formulated to use a script to check in advance which files VDF might ignore.
But it seems to me easier to let VDF do the work first and then see which files were actually not processed. - At least with respect to (a) and (b).

**Comment by gtTracy** [comment]
Thanks to both of you. I had completely overlooked that I could export the database to a JSON file - that will be much easier than the approach I was started down (which was to run ffmpeg against each file and see what kind of errors it produces - especially given that ffmpeg doesn't always produce an error exit code when it finds problems).

I think matching up with JSON with the file paths will give me plenty of information for finding likely problem files.

Thanks again.

**Comment by Maltragor** [comment]
If you like Python and don't have already anything that works better, you can play around with it:

```Python
import sys
import os
import enum
import json


class Flags(enum.IntFlag): 
    IsImage          =  1
    ManuallyExcluded =  2
    ThumbnailError   =  4
    MetadataError    =  8
    TooDark          = 16
    AllErrors        = ThumbnailError | MetadataError | TooDark
    AllNonErrors     = ManuallyExcluded | IsImage


def compare(config, database):
    with open(database) as fh:
        db  = json.load(fh)
    with open(config) as fh:
        cfg  = json.load(fh)

    dbFiles = set(item["Path"] for item in db)

    includes = cfg["Includes"]
    excludes = set(cfg["Blacklists"])
    flags = 0
    recursive = cfg["IncludeSubDirectories"]
    includingReadOnly = not cfg["IgnoreReadOnlyFolders"]
    followLinks = not cfg["IgnoreHardlinks"]  # c#: FileAttributes.ReparsePoint -> SymLink, no hardlink

    files = set()
    for rootdir in includes:
        for _folder, _subs, _files in os.walk(rootdir, followlinks=followLinks):
            if (not _folder in excludes) and (includingReadOnly or os.access(_folder, os.W_OK)):
                # TODO Maybe also skip some file extensions or small files....
                files.update([_folder + os.sep + f for f in _files])
            if not recursive:
                break

    print("\nFiles not scanned:")
    notScannedFiles = files.difference(dbFiles)
    for x in notScannedFiles:
        print(x)

    print("\nFiles ignored due to errors:")
    skippedFiles = {item["Path"]:Flags(item["Flags"]) for item in db if (item["Path"] in files.intersection(dbFiles)) and (Flags(item["Flags"]) & ~Flags.AllNonErrors)}
    # Or the next line to list all error flagged files of the database
    #skippedFiles = {item["Path"]:Flags(item["Flags"]) for item in db if (Flags(item["Flags"]) & ~Flags.AllNonErrors)}
    for x in skippedFiles.items():
        print(f"{str(x[1].value):>2}: {str(x[1].name):<18} {x[0]}")
    
   

# First parameter is the VDF path or the VDF settings file (in order to get the include and exclude directories and some settings)
# Second optional parameter is the ScannedFiles.db file (otherwise the ScannedFiles.db file is searched in the settings directory)
def parseArguments(args):
    if (len(args) >= 1) and (len(args) <= 2):
        if os.path.isdir(args[0]):
            config  = args[0] + os.path.sep + "Settings.json"
        else:
             config  = args[0]
        if len(args) == 2:
            database = args[1]
        else:
            database = os.path.dirname(config) + os.path.sep + "ScannedFiles.db"
        if os.path.isfile(config) and os.path.isfile(database):
            return (config, database)
    return None


if __name__ == '__main__':
    args = sys.argv[1:]
    result = parseArguments(args)
    if (result is not None):
        compare(result[0], result[1])
```

**Comment by gtTracy** [comment]
Sorry for the long delay - it's been a busy couple of days. And thank you for the code, although I had pretty much already put something together using bash and jq. I found that there were very few (approximately 20) files in the database that had errors, so I'm going to try tracking down which ones might not be getting picked up at all, then separate them into a set of folders - as well as putting a few "known" duplicates (things I've found as I'm sorting), and run just against those folders and see what happens. If I can track down any commonalities, I will post back (or if I find something that looks like it's going wrong with the program, I'll open a bug report).

May take me a few days to arrange this, though, as work has kind of gotten in the way (amazing how often it does that :-) )

**Comment by gtTracy** [comment]
Found two files that are essentially the same thing (visually, when played, they appear to be the same, or very similar). Moved them into their own folder, and ran VDF. First thing I did was clear the database, then set the program to only look in the folder where those two files are. Set for 5 thumbnails, and 100% similarity. Started the scan. The log shows that both files were scanned and added to the database. No duplication detected (I didn't expect it to find them duplicated, at 100%).

So, I started dropping the similarity by 1%, then scanning after each drop. The first time it found the files as similar was when I scanned at 79% similarity (and the thumbnails are different enough that I could see that). However, the displayed match shows a similarity of 89.216%, which confuses me as to why it didn't show the match until I got down to 79%....

Anyway, it appears that the program is looking at all the files (for the most part - I went back and rescanned the whole lot of them, and there were 65 files showing an error flag in the database, and the total number of scanned files differs from the actual number of files by a similar number), but that files that I see as visually similar aren't getting picked up as similar as soon as I might have thought they would. Perhaps this is down to minor differences in length (as I'm sure the thumbnails are generated at set intervals based on the length of the file)...?

**Comment by Maltragor** [comment]
> Perhaps this is down to minor differences in length (as I'm sure the thumbnails are generated at set intervals based on the length of the file)...?

Yes, the displayed thumbnails have a normalized time distance of 1.0/(NumThumbnails + 1). The normalized position is then multiplied by the respective video length.
And the similarity of a video is also determined based on (other) thumbnails at these time positions.

A different video length due to the fact that one of the videos contains an additional scene, opening credits, etc. is thus always less recognizable as a duplicate. A video that is only an excerpt from another video would in most cases not be recognized at all.

On the other hand, the approach of working with view fixed time positions allows a very fast initial scan (database creation) compared to other strategies.
Otherwise, one would have to search the videos for scene changes or identify characteristic features, which would significantly increase the processing time per video.

**Comment by gtTracy** [comment]
That makes sense. I was originally expecting that the opening frame of the video might be one of the thumbnails (which would have raised the percentage match significantly in this case, as the first 15 to 20 seconds of the two videos are pretty much identical). In looking at the videos, I'm not sure how they are getting off sync - as they are the same video, just different copies. It's almost like one is being played a tiny bit slower than the other (for instance, the third thumbnail on each of the videos looks like they are within 30 frames of each other - think someone moving their hand from their face to their side, where the first video catches them with their hand at shoulder level, while the second video is at waist level, that's how close they are in terms of the action). But regardless, the original question is now answered, and I can see how they didn't show up in the original matching process.

I had thought about asking if there could be an option to compare frames from the first 30 to detect matching videos, but then realized that a lot of videos have "logo" screens at the beginning, which would return a high percentage of false positive matches...

**Comment by Maltragor** [comment]
> The first time it found the files as similar was when I scanned at 79% similarity (and the thumbnails are different enough that I could see that). However, the displayed match shows a similarity of 89.216%, which confuses me as to why it didn't show the match until I got down to 79%

VDF determines the similarity of the video by comparing the individual thumbnails (Where they are not the ones displayed, but the time positions are the same).
The comparison of each thumbnail pair is matched against the specified limit. So if a thumbnail pair does not reach the limit, the video is sorted out. The final similarity displayed is the average of all comparisons.

Whether this is good or bad should depend on the scenario. For a video with a slight time offset and the desire to still recognize it well, it is probably rather unfavorable. Because here a scene change or major change in one of the thumbnails can occur that one would actually rather have ignored. On the other hand, so the thing with the temporal offset excluded, two videos with partly different scenes are just different.

**Comment by gtTracy** [comment]
Yes. And to help combat that situation, I typically do 5 searches for
matches at each percentage. First is 100% match with 5 thumbnails, then 99%
with 5 thumbnails, then 98% then 97% then 96%, then do the series again
with only 4 thumbnails, then again with 3, then again with 2, then again
with 1. That's why I was surprised to find duplicates when sorting - I had
thought that series of tests would be sufficient. Apparently not, though,
so I will have to come up with a more extensive set of tests.

**Comment by 0x90d** [comment]
Closing as the original question seems to be answered.
