### ISSUE TITLE
VDF infinite crash due to database error

### ISSUE THREAD

**Issue by scrapix** [0x90d/videoduplicatefinder#247]
**Environment**
 - OS: Windows

**Describe the bug**

- Computer crashed while performing VDF scan.
- Restarted computer.
- Opened VDF
- VDF shows error and crashes due to database error
- Not possible to start VDF anymore. Always shows the same error and crashes again

**Expected behavior**

VDF should be startable in any case. 
In case of database error, the previous, working database file should be restored. 

**Maybe possible fix**

- Duplicate ScannedFiles.db to ScannedFiles.db.tmp to work on when starting a VDF scan
- on successfull scan finish overwrite the ScannedFiles.db with ScannedFiles.db.tmp
- In case of an error the original ScannedFiles.db is still there for use

![VDF-1](https://user-images.githubusercontent.com/23144020/144698326-cba7243e-ddd8-45c7-b88e-e873f2e525cf.png)
[log.txt](https://github.com/0x90d/videoduplicatefinder/files/7653338/log.txt)

**Comment by 0x90d** [comment]
The scan must have been finished otherwise there wouldn't be errors saying it cannot read the scan results file (which is a different file than the database). I would rather assume that the crash has broken these files. Your possible fix wouldn't help here. But it still may be a good to have a backup functionality which before a scan starts just make a backup of the database at a user defined location and leave it there.

**Comment by Maltragor** [comment]
Let's consider the following two aspects separately: (A) VDF's behavior in case of corrupted files and (B) how to avoid such a situation.

A) 

i) `ImportScanResultsIncludingThumbnails()` catches any exception while importing from json and rebuilding the view. If an Exception occurs only the error message is shown and VDF keeps running. -> OK, no problems.

ii) `LoadDatabase()` catches only `ProtoException` and returns false if `ProtoException` is raised while both (new and old format) loading attempts. In MainWindowVM.cs, `LoadDatabase()` there is an `Environment.Exit(-1);` if `LoadDatabase()` returns `false` and the "Failed to load database of scanned files. Please see log file in VDF directory" Message is shown. So in this case (see screenshot) VDF did not crashed but terminates intentionally. 
Whereby the question is whether this makes sense. The broken ScannedFiles.db could in principle also be deleted or renamed and VDF could then continue to run.
In addition there is at least one unhandled scenario of file corruption which lets VDF crash.
I had managed it only once (on the first try ;-) ) by running VDF in the debugger and probably killed it exactly while writing the database file. But it can be reproduced easier by cutting off the end of the binary ScannedFiles.db file. In both cases a "System.IO.EndOfStreamException" : 'Attempted to read past the end of the stream.' will raise (and should be handled.)

B) 

i) SaveDatabase() overwrites ScannedFiles.db, so interrupting the write action may result in a corrupted file. 
If you want to change the behavior without the aspect of a backup per scan, I would not copy the ScannedFiles.db every time, but let SaveDatabas write a file with a different name and then at the end make by deleting / renaming the names change again or always keep the previous version and load the latest file based on the timestamp and in case of error fall back to the older state,.. etc..

ii)
> have a backup functionality which before a scan starts just make a backup of the database at a user defined location and leave it there.

But in this case I would wish that this only happens if the file has changed. 
Usually you will scan several times with different parameters (at least I do it that way) and don't want an identical copy of the database file for each run.
Or Maybe just an database export / import menu item.

**Comment by 0x90d** [comment]
> but let SaveDatabas write a file with a different name and then at the end make by deleting / renaming the names change again

That sounds reasonable, especially as moving/renaming on same drive is performed instantly.
