### ISSUE TITLE
GUI freezes up on lots of duplicates

### ISSUE THREAD

**Issue by 0x90d** [0x90d/videoduplicatefinder#25]
Due to 6a87099ed177c026a84e2018335af015ac011fc5 the windows GUI freezes up on end of scan when lots of duplicates have been found and its processing the thumbnails. We probably have to make it run deferred in background

Another issue: Start scan button becomes available although its still busy loading the thumbnails. It should be blocked or we have to abort gathering thumbnails when the user clicks on start scan again.

 cc: @naxolotl

**Comment by Revan654** [comment]
> 
> 
> Due to [6a87099](https://github.com/0x90d/videoduplicatefinder/commit/6a87099ed177c026a84e2018335af015ac011fc5) the windows GUI freezes up on end of scan when lots of duplicates have been found and its processing the thumbnails. We probably have to make it run deferred in background
> 

I have a massive list at the end, but I haven't ran into any freezing. One thing to consider, is sometimes the drive has to wake up and because of that is can lock up the software for a few seconds. My main drive is also a M.2 drive which could be preventing some of the freezing that could happen if you have a standard harddrive.

**Comment by beezischillin** [comment]
I ran it through a few terabytes of data and it's freezed up on me. Currently it's at 10 gigs of ram / 8% of usage on an 8-core, 16 thread Ryzen. It would be nice if it didn't happen and instead there was some sort of visible progress. Is it solvable?
