### ISSUE TITLE
ffmpeg shared libraries error message is cut off

### ISSUE THREAD

**Issue by newadventure079** [0x90d/videoduplicatefinder#271]
**Environment**
 - OS: macOS

**Describe the bug**
The error message describing the ffmpeg shared libraries not being able to be found is cut off

**Expected behavior**
To be able to fully read the error message

![Screen Shot 2022-01-10 at 3 34 41 PM](https://user-images.githubusercontent.com/84156407/148849845-53c8471e-83ec-4b8a-8ae1-e9572c0994b3.jpg)

**Comment by 0x90d** [comment]
If you mouse hover the text message, does a scrollbar appear? Unfortunately the current message box uses a couple of workarounds for existing Avalonia bugs, all because Avalonia cannot have a fixed sized window + which cannot be maximized + and which content is a string, which should be text wrapped + the window size is based on the width of the string + but has a maximum. All of this is necessary to have a true message box effect. As long as this is not supported by Avalonia, there will be always problems with it. But I think each error is also logged, so you could see the full message there.

**Comment by newadventure079** [comment]
A scrollbar does not appear on hover.  The text can't be double clicked either which would allow for highlighting and copying

**Comment by 0x90d** [comment]
This needs to be addressed by Avalonia
