### ISSUE TITLE
Failed to open VDPAU backend libvdpau_va_gl.so

### ISSUE THREAD

**Issue by Ynjxsjmh** [0x90d/videoduplicatefinder#291]
**Environment**
 - OS: Arch Linux x86_64

**Describe the bug**

When I run `./VDF.GUI` in command line and scan the selected folder, it will output following message continuously:

```
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
```

Though it outputs the above error, the program works fine and can show the possible duplicate videos.

**Comment by Maltragor** [comment]
Assumption about your VDF configuration:
- Use native Ffmpeg binding: [NO]
- Hardware Acceleration: [vdpau]

=> VDF executes ffmpeg with parameter `-hwaccel vdpau` to generate the thumbnails.
Obviously there is a problem with VDPAU on your system. 
_(Probably VDPAU automatically tries other configurations or the missing file is not mandatory, so that it works in the end. If I do not explicitly set the environment variable LIBVA_DRIVER_NAME, for example, an attempt is first made with the wrong driver before the working one is selected)._

You can run `vdpauinfo` (and `vainfo`) to get more information about the initialization process.
Unfortunately I can't offer you a concrete solution, but:

a) If 
- Use native Ffmpeg binding: [YES]
- Hardware Acceleration: [none] _(\*)_

works for you, I would prefer that anyway, as it is much faster. 
_(\*) If that works you can of course also try hardware acceleration._

b) Maybe vaapi works without errors
c) The VDPAU problem has nothing to do with VDF and others have reported such problems. Maybe there is also a helpful answer.

**Comment by Ynjxsjmh** [comment]
> Obviously there is a problem with VDPAU on your system.

Thanks for pointing that out, I try to search what VDPAU is and find it is related with NVIDIA GeForce 8 GPU. My computer doesn't have GPU, the problem might be here.

```bash
$ lspci | grep VGA                                                                                                ─╯
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)

$ vainfo                                                                                                          ─╯
vaInitialize failed with error code -1 (unknown libva error),exit

$ vdpauinfo                                                                                                       ─╯
display: :0   screen: 0
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
Error creating VDPAU device: 1
```

**Comment by Maltragor** [comment]
VDPAU is an library and API originally designed by NVIDIA but it is not limited to NVIDIA GPUs.
And on the other hand it is not the only API for GPU hardware acceleration support (and not the only one supporting NVIDIA GPUs).

E.g.: https://wiki.archlinux.org/title/Hardware_video_acceleration

On my system the _libva-intel-driver (i965)_ i965_drv_video.so is used by VA-API directly and through the 'OpenGL/VAAPI backend' by VDPAU. 
Besides this driver there is another one for intel graphics: _intel-media-driver (iHD)_ 

On my Linux Mint the driver was automatically installed and worked. Maybe there is a little more to do on an Arch Linux^^.

**Comment by Ynjxsjmh** [comment]
Thank you, my default VDF configuration is:

- Use native Ffmpeg binding: [NO]
- Hardware Acceleration: [auto] -> which seems to detect to use vdpau

![image](https://user-images.githubusercontent.com/40143136/151824858-0c5bba16-8c16-4ad9-a9c0-78a8947dab00.png)

After seeing that archlinux wiki about hardware acceleration, I notice I might miss some libs:

![image](https://user-images.githubusercontent.com/40143136/151826134-be9970a2-97fc-4adb-ac15-9f9602ab1d93.png)

After installing `libvdpau-va-gl`, `vdpau` works without any errors.
