### ISSUE TITLE
App not honoring "exclude hardlinks"

### ISSUE THREAD

**Issue by masterofobzene** [0x90d/videoduplicatefinder#298]
**Environment**
 - OS: Windows 10 latest updates

**Describe the bug**
![imagen](https://user-images.githubusercontent.com/94469116/153199750-de978768-5bef-454b-92f7-19da684496ee.png)

I keep getting dups when they are really hardlinks.
Note that the problem are not SYMLINKS folders but HARDLINKS files

**Expected behavior**
The app should recognize and ignore hardlinks when this option is activated.

**Comment by Maltragor** [comment]
See my comment in: #259

**Comment by masterofobzene** [comment]
> See my comment in: #259

Sorry but... what do I have to do with your comment? I'm no dev. 
Do I have to delete my database and start again? if that's what you suggest, I can confirm _this doesn't solve anything_ since I just deleted the whole app directoy, then extracted the whole program files again from the latest version. So I "started from scratch" and I can also confirm that the option to exclude hardlinks was ticked before the "first" scan.
Still getting  70% hardlinks to files (videos, images). 
Symlinks on the other hand, seem to be ok (folders).

**Comment by Maltragor** [comment]
The comment was intended to express:
- VDF has a functionality to ignore certain types of linked files. This functionality, called "Exclude Hardlinks", has (or at least had at the time of the comment) the limitation that it only works if the files are not yet in the database, i.e. VDF is scanning them for the first time.
- That I consider the naming of the functionality "Exclude Hardlinks" as unfortunate chosen, respectively I actually assume that it is wrong and just no hardlinks are excluded. (I differentiate this at the point, since I had not tested it explicitly under Windows). But the functionality checks for something called ReparsePoint. And this mechanism is used by NTFS for symbolic links and junction points, whereas hard links work differently. (https://en.wikipedia.org/wiki/NTFS_links). Moreover, only for symbolic links (/ reparse points) there is a distinction between original and link. With hard links there is no such separation at all. 

So the comment was not a solution how to get it to work.

It was more the information that a revision of both the name and functionality of this feature needs to be looked at more closely from my point of view and why I think so.

I deliberately left everything else open and kept it short by referring to the old comment.
Because on the one hand it could be that the knowledge about the behavior of the functionality is already enough as an answer, on the other hand one could take it as a reason to discuss about name and functionality - and that finally separately regarding symbolic links and hard links. Because with the latter one would have to clarify which behavior one expects at all. Excluding all hard links would mean, due to the lack of an original vs. link distinction, that the files are completely ignored, which would of course be a different behavior than with the symbolic links. Or you could define a rule that determines which file is included in the search if several hard links to this file exist. (e.g. first found, shortest path, alphabetically first,...).

**Comment by Maltragor** [comment]
@masterofobzene

Files:
file_A.mp4, file_B.mp4
symlink_to_A.mp4
hardlink_to_A.mp4

file_A.mp4 and file_B.mp4 are similar but different.

If you have file_A.mp4, file_B.mp4, symlink_to_A.mp4 and ignore all (symbolic) linked files, you keep file_A.mp4, file_B.mp4 and find out that they are similar. (Because the system knows that symlink_to_A.mp4 is a link to file_A.mp4, so you can keep the original file)

If you have file_A.mp4, file_B.mp4, hardlink_to_A.mp4 and ignore all (hard) linked files, you keep only file_B.mp4 and lose the opportunity to find out that file_B.mp4 is similar to another video in your collection. (Because the system only knows that there is a data block on disk addressable by file name file_A.mp4 as well as hardlink_to_A.mp4, so there is no original or link but only two different file names (+meta data))
But I would expect to keep one of the two hard linked files. Since there is only the knowledge that file_A and hardlink_to_A refer to the same data on the disk an additional rule based on file date, name or search order has to determine which file is kept.

**Comment by masterofobzene** [comment]
@Maltragor 

Mmm.. I don't think thats how it works.

file_A.mp4 and file_B.mp4 are similar **but different.**
`
If you have file_A.mp4, file_B.mp4, symlink_to_A.mp4 and ignore all (symbolic) linked files, you keep file_A.mp4, file_B.mp4 and find out that they are similar. (Because the system knows that symlink_to_A.mp4 is a link to file_A.mp4, so you can keep the original file)`
This should be it, yes.

`If you have file_A.mp4, file_B.mp4, hardlink_to_A.mp4 and ignore all (hard) linked files, you keep only file_B.mp4 `
NO. Why? I don't lose anything. I didn't delete anything, thats a furter step. And you keep file_A and all its hardlinks are NOT TAKEN INTO ACCOUNT while scanning. **That should be the expected result if this setting worked as it is named.**

 `and lose the opportunity to find out that file_B.mp4 is similar to another video in your collection. `
If file B is not EQUAL to file A and its not a hardlink, then it should be scanned normally. Why you say it doesn´t?. Anyway suppose the files are REALLY similar (i.e. arm is in different position) then the program should show it as a similar file anyway but not the hardlinks. That is how one expects a setting called "exclude hardlinks" to work at least. To discard all hardlinks, because they are dups made on purpose.

`(Because the system only knows that there is a data block on disk addressable by file name file_A.mp4 as well as hardlink_to_A.mp4, so there is no original or link but only two different file names (+meta data))`
But I would expect to keep one of the two hard linked files.`
**Here is what is important. OS restriction to identify hardlinks.**
Which file is the "original" is not important. You SHOULD know (because you made the hardlinks) which file is where you want it to be based on the path. The file still exists _**until**_ all hardlinks and source are deleted.

**Comment by masterofobzene** [comment]
Closed but no solution. Sadly this software is not very reliable.
