### ISSUE TITLE
cant find ffmpeg when selested to use it

### ISSUE THREAD

**Issue by rezad1393** [0x90d/videoduplicatefinder#315]
**Environment**
archlinux

**Describe the bug**
I set to use native ffmpeg
I downloaded from ffmpeg website the static ffmpeg v4 and put the ffmpeg and ffprobe in the vdf folder (beside the app and dll) 
but it says that it cant find ffmpeg

btw when I uncheck that option , it works
I am confused as to what that option means even if it says it is much faster.
does it mean that downloaded ffmpeg is faster that the os provided ffmpeg?

**Comment by Maltragor** [comment]
VDF can use ffmpeg in two ways:
a) By executing the ffmpeg (and ffprobe) **applications**, as if you were running the programs yourself from the command line.
b) By calling only the relevant functions of the ffmpeg **libraries**, but not executing the program itself. VDF calls this mode **_native ffmpeg_**.

_Briefly a few general remarks:
An application / executable is a file that can be executed by itself. It usually calls functions from libraries. A library can be linked statically or dynamically. In the first case it becomes a fixed part of the application, in the second case it remains an independent unit / file, which can be used also by other applications (-> **shared**)._

So that VDF can work in the "native ffmpeg" mode (b), ffmpeg must be made available in the variant, in which the libraries are still available (shared version).
=> You write that you downloaded `static ffmpeg`, so that was the wrong version^^. You need the `shared ffmpeg` version, as described in the VDF readme.

Whereas you should be able to install ffmpeg via the "package manager" on Linux, as @kattjevfel already mentioned. _(I have never tried it myself in archlinux, but in Linux Mint)._

So the higher speed of the _native ffmpeg mode_ has nothing to do with different ffmpeg versions / sources.
The significantly better performance results from the fact that to extract the thumbnails, it is not necessary to spawn a new ffmpeg process each time, forward the data to VDF via pipes, etc.... but only call the required ffmpeg library functions.

**Comment by rezad1393** [comment]
good info.
my issue is that in the readme page it says get the **full** shared.
full usually means statically linked , as in you dont need to have anything else installed from your os jost package manager to run it.
and so I thought shared meant that this full binary was shared by all distros.

when I read your text I get the impression that I need to install the ffmepg from my distro package manager (that would be a non-static version) which I have.

but then in readme it say to copy it in the folder. which means that vdf doesnt use my  os ffmpeg if I select native mode and I need to copy something (fffmpeg and ffprobe binary ) to its folder. usually you would copy static-linked binary to a portable folder to run them not a linked-one (or as you call here shared one).

so I am now double confused.

because my os binary is library lineked-one (please dont use shared name) but vdf cant use the native mode with it because it is not copied in is own folder? but it can run in directly when uses the non-native option?

and honestly the naming sucks. why call it native when it doesn't use OS native binary directly? is I deselect native I can see that vdf runs ffmpeg directly (my os native binaries).

**Comment by rezad1393** [comment]
if I read the readme on github page and I didnt know about the native  vdf before I would have read that as meaning a depecdency requirement just like firefox needed pulseaudio.
and I would have read the link to ffmpeg shared version as isntruction to install my os ffmpeg because there is two version on that sites.
one is static that you say is not the one. and another is the deb or rpm for debian or redhat based os which usually means installed them to the package manager and not copiing to vdf folder because they are dynamic-linked binaries.

**Comment by rezad1393** [comment]
and after saying all of this why not make vdf load the shared version from the os folder?
is that a programing issue that would force it you launch a separate exe process?

**Comment by rezad1393** [comment]
> 

I think this was the correct answer.
I removed 4.4 in the past because I didnt need it.

any plan to use 5?

**Comment by 0x90d** [comment]
5.0 support is tracked here #309 until then @Maltragor pretty much explained how you can get it to work.

**Comment by Maltragor** [comment]
> so does vdf uses a verisoned number?

VDF uses the major version numbered filenames. E.g. "libavcodec.so.58"
First VDF searches in the VDF subdirectories where you should copy ffmpeg according to the readme. If this fails, the os function for loading the libraries is called without specifying a path, so the os will try its default strategies to find the libraries. (And if this fails in a last step subdirectories of /usr/ starting with "lib*" are searched for the libs.)

> and after saying all of this why not make vdf load the shared version from the os folder?

VDF will load it from the os folder. The download and copy to VDF folder variant primarily targets windows and is an additional option if you want to use a specific ffmpeg minor version / build independent of the system.

Expected libs: `{name, major version} ` -> `name.so.version`
_I am too lazy to reformat the notation^^ The representation is simply taken from a source code section._
{"avcodec", 58},  {"avdevice", 58},  {"avfilter", 7},  {"avformat", 58},  {"avutil", 56},  {"postproc", 55},  {"swresample", 3},  {"swscale", 5}

**Comment by rezad1393** [comment]
> VDF will load it from the os folder. The download and copy to VDF folder variant primarily targets windows and is an additional option if you want to use a specific ffmpeg minor version / build independent of the system.

I typed that before trying the ffmpeg4.4
sorry.
but in my defence usually apps just load the libavcodec.so.
thought using the major version is a good way to ensure that things moves with the correct library so I can fault you there.

btw this versioning reminds me, is there any plan for a flatpak version?

also any plan to move from .net? maybe to QT? I know you want windows to run it too but QT has good windows libs too.
although this is more of a long term goal maybe.
