### ISSUE TITLE
Unable to load DLL 'avformat.58 under /Applications/videoduplicatefinder': The specified module could not be found.

### ISSUE THREAD

**Issue by newadventure079** [0x90d/videoduplicatefinder#319]
**Environment**
 - OS: macOS

**Describe the bug**
```
04:26:16 => Failed using native FFmpeg binding on xxx, try switching to process mode. Exception: System.DllNotFoundException: Unable to load DLL 'avformat.58 under /Applications/videoduplicatefinder': The specified module could not be found.
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName, Boolean throwException)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__6_319()
   at VDF.Core.FFTools.FFmpegNative.VideoStreamDecoder..ctor(String url, AVHWDeviceType HWDeviceType) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.Core\FFTools\FFmpegNative\VideoStreamDecoder.cs:line 50
   at VDF.Core.FFTools.FfmpegEngine.GetThumbnail(FfmpegSettings settings, Boolean extendedLogging) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.Core\FFTools\FfmpegEngine.cs:line 50
```
I have a `avformat-58.dll` but not a `avformat.58.dll`.  I downloaded `ffmpeg-n4.4-latest-win64-gpl-shared-4.4.zip`

**Expected behavior**
No errors

**Comment by 0x90d** [comment]
See #309

**Comment by newadventure079** [comment]
In the root folder

**Comment by 0x90d** [comment]
> * OS: macOS

You have macOS but you downloaded the windows version of ffmpeg ffmpeg-n4.4-latest-**win64**-gpl-shared-4.4.zip, that cannot work. You must get a macos build of ffmpeg.

**Comment by newadventure079** [comment]
But macOS doesn't have .dll files so that's why I downloaded the Windows version, since the app is cross platform

**Comment by newadventure079** [comment]
Also, there's no mac builds here https://github.com/BtbN/FFmpeg-Builds/releases

**Comment by Maltragor** [comment]
> But macOS doesn't have .dll files

The fact that the term DLL may be used in the context of VDF is probably due to the fact that VDF is a .net application. And .net has its origin in Windows, the world of DLLs.
Other operating systems use other file formats for their **native** libraries. 
From therefore I would not take e.g. with the error outputs the term DLL so literally.

> Also, there's no mac builds here ...

But the link from the readme leads to https://ffmpeg.org/download.html
And there is also a button with a bitten apple on it. 
In addition there seem to be other ways to install such packages under macOS like Homebrew or MacPorts. (I have no idea about the Mac world,... just did a quick search)

--------
But now to the really interesting point:

@0x90d: Does VDF support the ntive ffmpeg mode at all under macOS?
`CheckForFfmpegLibraryFilesInFolder()` only has the distinction for Linux and otherwise searches for the Windows dlls. I would expect that at least at this point the macOS case has to be distinguished as well so that the proper filename pattern can be used.

**Comment by Maltragor** [comment]
@newadventure079:
But you can try to copy the macOS libraries into the directory with the Windows ffmpeg dlls. This should be enough as a workaround for the CheckForFfmpegLibraryFilesInFolder() thing. Whether it works then however altogether I do not know.

**Comment by newadventure079** [comment]
The ones at https://ffmpeg.org/download.html#build-mac are static build and not the shared builds vdf requires

**Comment by 0x90d** [comment]
> Does VDF support the ntive ffmpeg mode at all under macOS?

According to https://github.com/Ruslan-B/FFmpeg.AutoGen#usage it should support macOS using homebrew's installation, but it needs to set path to ffmpeg libraries which I believe VDF currently does not.

**Comment by Maltragor** [comment]
Regarding #323 (and #325):
I was about to write in closed issue #325 that especially after looking into the code again, I assume that the windows dlls are completely ignored.
Issue #323 seem to confirms this once again.

For the explicit search of the libraries around `CheckForFfmpegLibraryFilesInFolder()` two paths are checked initially. The `/bin` directory (without further preconditions) and the VFD root directory, if the ffmpeg binary was found there before. Under Windows the `ffmpeg.exe` is searched for, otherwise `ffmpeg`.
So under macOS the existence of `ffmpeg` is required for the directory to be taken into account. However, the file of course is not present in the Windows zip, consequently the DLLs in the root directory are also ignored.
In the `/bin` directory, however, the Windows dlls would be found.

=> This means that the attempt to load the Windows DLLs does not work (/bin, #323). Whereas in the root directory (due to the lack of ffmpeg binary) the DLLs are ignored and the fallback takes effect:
https://github.com/0x90d/videoduplicatefinder/blob/80db0011a5ec9359cdbb35dc759335c12532fe35/VDF.Core/FFTools/FFmpegNative/FFmpegHelper.cs#L57-L62

_If my (not verified) assumption is correct_, 
after you have installed ffmpeg with homebrew, it should still work completely without the windows ffmpeg DLLs. 
Have you ever deleted them completely and tried it?
And secondly, it would mean that homebrew installs the libraries in a way that they are automatically found by the system, just like with a package manager under linux.

**newadventure079** listed in #325 the directory structure of his homebrew ffmpeg directory.
To adapt  `CheckForFfmpegLibraryFilesInFolder()` analogously to the other operating systems, one would obviously search for something like libavcodec.59.dylib (`$"lib{item.Key}.{item.Value}.dylib"`).

**Comment by newadventure079** [comment]
#323 is about the dlls not getting picked up in a subdir named bin in the root of the VDF folder. ie. `/VDF/bin` not `/bin`. Instructions state `... Or into a sub folder called bin`.  They are picked up and used if they are placed in the root of VDF

> Have you ever deleted them completely and tried it?

Yes, on a brand new VDF install, native ffmpeg bindings aren't found, even with previously installing ffmpeg and having it in my $PATH and all that.  It's only after I drop in the Windows dlls does native ffmpeg bindings work.  I know this because then I dont get the error message that native ffmpeg bindings couldn't be found and also because the scan is MUCH faster

```
cd /opt/homebrew
find . -name 'libavcodec.59.dylib'
./lib/libavcodec.59.dylib
./Cellar/ffmpeg/5.0.1/lib/libavcodec.59.dylib
```
So it looks like `libavcodec.59.dylib` is in `/opt/homebrew/lib`
```
ls -l /opt/homebrew/lib/libavcodec.59.dylib
lrwxr-xr-x  1 me  admin  61 Jun 20 01:19 /opt/homebrew/lib/libavcodec.59.dylib@ -> ../Cellar/ffmpeg/5.0.1/lib/libavcodec.59.dylib
```
So I'd probably put the `Ffmpeg.RootPath` as `/opt/homebrew/lib` for macOS

**Comment by Maltragor** [comment]
> https://github.com/0x90d/videoduplicatefinder/issues/323 is about the dlls not getting picked up in a subdir named bin in the root of the VDF folder. ie. /VDF/bin not /bin. Instructions state ... Or into a sub folder called bin. 

I know, that's what I meant too, so  the two directories `/VDF` and `/VDF/bin`.
But indeed that was not really clear from my wording.

Again back to my assumption and and what also speaks for it:
From FFmpeg.AutoGen (the ffmpeg binding used by VDF):
->  FFmpeg.AutoGen puts the library name together depending on the operating system. *.dylib on macOS, *.dll on windows when  calling `LoadNativeLibrary()`. This also speaks for the fact that the dlls would not be used.
```c
switch (GetPlatformId())
{
      case PlatformID.MacOSX:
            GetNativeLibraryName = (libraryName, version) => $"lib{libraryName}.{version}.dylib";
            break;
      case PlatformID.Unix:
            GetNativeLibraryName = (libraryName, version) => $"lib{libraryName}.so.{version}";
            break;
      case PlatformID.Win32NT:
      case PlatformID.Win32S:
      case PlatformID.Win32Windows:
            GetNativeLibraryName = (libraryName, version) => $"{libraryName}-{version}.dll";
            break;
```

https://github.com/Ruslan-B/FFmpeg.AutoGen/blob/24da0e7cd0db359f817f3e3ddf947940a2e9b368/FFmpeg.AutoGen/Native/LibraryLoader.cs

---------------------

To avoid any misunderstandings regarding:

> Yes, on a brand new VDF install, native ffmpeg bindings aren't found, even with previously installing ffmpeg ...

So if you:
1: Extract VDF, run it and change settings to native ffmpeg, no HW Acceleration
2: Select a folder with at least two duplicated videos
3: Press Scan
=> VDF shows the following Error dialog?
![grafik](https://user-images.githubusercontent.com/36803696/174908856-f4affa73-5136-4672-9320-b34a5586c794.png)

4: Close VDF and copy the the windows ffmpeg dlls into the root folder of this VDF (i.e. /VDF) (and nothing else)
5: Run VDF and press Scan
=> The two videos are found, no errors appear in the log?

If that were the case for the two scenarios, I suffer absolutely no explanation as to how that could come about.

**Comment by newadventure079** [comment]
That's exactly correct, except there is an error message in the log `Unable to load DLL 'avformat.58 under /Applications/videoduplicatefinder': The specified module could not be found`, which is what this issue is all about.

Like I said in another comment, it'd be nice to put in the logs where VDF is searching for the ffmpeg native bindings and also if some are found, where it got them from.
