### ISSUE TITLE
some small features that will improve it a lot

### ISSUE THREAD

**Issue by nwgat** [0x90d/videoduplicatefinder#36]
* Compare more than one frame, as some files might have the same scene like a opening or recap before the new content comes
* Double Click to Play in System Media Player
* Use MediaInfo as a alternative

**Comment by nwgat** [comment]
i love it but atm its giving me false positives when it only compares one frame :(

**Comment by 0x90d** [comment]
- There is an option to compare more than one frame. Just increase the thumbnail count in GUI which is set to 1 by default.
- If you double click on the preview image it should open the file. 
- Why should it use mediainfo? Whats the benefit?

**Comment by Revan654** [comment]
> 
> 
>     * There is an option to compare more than one frame. Just increase the thumbnail count in GUI which is set to 1 by default.
> 
>     * If you double click on the preview image it should open the file.
> 
>     * Why should it use mediainfo? Whats the benefit?

-MediaInfo actually has a proper SDK you can use and easier to call what data you want. Then if you wrap it around IDisposable and native loading. The system will do all the work for you(Plus it's faster). no console output is required.
- MediaInfo is more accurate and easier to call what metadata you want(EX: MediaInfoStreamKind.General, "OverallBitRate_String").

- Speaking of preview image function, The whole double click method you use breaks the MVVM pattern. You used click MVVM must be tied to command if you want to stick with MVVM pattern all the way through. If you want to fix it look into using interactivity triggers. I personally use attached messaging system.

FYI, You might want to consider raising the security level required, Without running the program with admin rights. It blocks all files trying to be moved to the Recycle bin. This is due to Windows 10 additional security features that like to hijack the rights to all folders including external drives or just have the program delete the files from the current location.

**Comment by 0x90d** [comment]
Closing this as questions have been answered. Mediainfo may be added with a PR if there is real interest into this one.
