### ISSUE TITLE
Can anybody explain filters?

### ISSUE THREAD

**Issue by masterofobzene** [0x90d/videoduplicatefinder#364]
![1](https://user-images.githubusercontent.com/94469116/211219417-40d8df42-93cc-45bd-af6b-1361ea8006c5.jpg)

No hints, no wiki, no documentation so I'm forced to ask here.
Can anybody explain how to use those options?

**Comment by 0x90d** [comment]
It appears you are using an older version of VDF. However `File Size` is probably self explained. On File Path you can define which files are part of the scan or not, depending on a part of their file names.

For example you want to include only files which file names contain: `water`
Then `File Path contains` is set to `*water*`
But you want to exclude all files which file names contain: monkey
Then `File Path does NOT contain` is set to `*monkey*`

Then a file named `monkeys_drinking_water.mp4` is not part of the scan. But a file called `humans_drinking_water.mp4` is part of the scan. A file named `sample_video.mp4` is not part of the scan, because it doesn't contain `water`.

You could also exclude all files which contain blub and have a mkv extension. Filter would be `*blub*.mkv`
