### ISSUE TITLE
Better way to save the configuration ?

### ISSUE THREAD

**Issue by jlesage** [0x90d/videoduplicatefinder#377]
**Environment**
 - OS: Linux

**Describe the solution you'd like**

Somehow related to #376.

Currently, the configuration is automatically saved when user closes the VDF window.  The other method to save the configuration is via the "Save To File" button, which looks like more an export function.

Would it be useful to automatically save the configuration after a change?  Or maybe have a "Save Now" button (to save configuration without asking the user the location of the file) ?

I'm thinking about situations where configuration changes might be lost, because the application or the system crashes, power lost, etc.

**Comment by Maltragor** [comment]
Since the #376 is already closed...:
One possibility would be the class `PosixSignalRegistration`  introduced with .Net 6

Following is an extended version of `App.xaml.cs` to demonstrate this.
_The whole thing is just a "I'll try if it works in principle", therefore only as code snippet and not as PR._
_(RegisteredSignals is only used to prevent the garbage collector from disposing the returned instance)_

Calling `ApplicationHelpers.CurrentApplicationLifetime.Shutdown()` will also trigger `MainWindow_Closing()` with `ConfirmClose()` and so could prompt for user action. This would probably not be so good and would have to be changed. 

```c#
using Avalonia;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Markup.Xaml;
using Avalonia.Threading;
using VDF.GUI.Data;
using VDF.GUI.ViewModels;
using VDF.GUI.Views;
using System.Runtime.InteropServices;

namespace VDF.GUI {
	public class App : Application {
		public override void Initialize() => AvaloniaXamlLoader.Load(this);
		private static void OnTerminationSignal(PosixSignalContext context)
		{
			Console.WriteLine($"\n{context.Signal} fired");
			Dispatcher.UIThread.InvokeAsync(() => ApplicationHelpers.CurrentApplicationLifetime.Shutdown()).Wait();
			Console.WriteLine("done");
		}

		private static List<PosixSignalRegistration> RegisteredSignals = new();

		public override void OnFrameworkInitializationCompleted() {
			if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop) {
				desktop.MainWindow = new MainWindow {
					DataContext = new MainWindowVM(),
				};
			}

			base.OnFrameworkInitializationCompleted();
			SettingsFile.Instance.HardwareAccelerationMode = ApplicationHelpers.MainWindow.InitialHwMode;

			RegisteredSignals.Add(PosixSignalRegistration.Create(PosixSignal.SIGTERM, OnTerminationSignal));
			RegisteredSignals.Add(PosixSignalRegistration.Create(PosixSignal.SIGINT,  OnTerminationSignal));
		}
	}
}
```

**Comment by jlesage** [comment]
Thanks!
