### ISSUE TITLE
Add option to copy filename to clipboard

### ISSUE THREAD

**Issue by David-Maisonave** [0x90d/videoduplicatefinder#388]
**Environment**
 - OS: Any
 
**Describe the solution you'd like**
Add "Copy filename to clipboard" option to the context menu.
Add "Swap filenames" option to the context menu.

When I'm reviewing duplicate videos, sometimes the video with the lower resolution has the preferred filename, so before deleting it, I have to copy the file name and rename the higher resolution video to that name. A copy file name feature would make this much easier. 

A swap filenames option would make it even easier.

**Comment by 0x90d** [comment]
Swap filenames have been requested before. The problem is that you can select more than 2 items. So which ones are going to swap the filename? Because of that the feature hasn't been added. Copy filename to clipboard makes sense.

**Comment by Maltragor** [comment]
Some thoughts on the topic:

> Swap filenames

From my point of view, it would be the most intuitive (if Avalonia allows it):
- Duplicates or their selection checkboxes do not matter.
- Instead, any two files are to be selected by row multi-select.
- Unless exactly two rows are selected, "swap filenames" is grayed out or completely hidden in the context menu. 
(If it were not so easy to do this with Avalonia, the entry would always be displayed normally and if clicked with != 2 an info-box would be displayed explaining that two rows needs to be selected to swap names.)


> Copy filename to clipboard

There could be two use cases for such a function:
1. In order to be used in the context of file renaming
-> For this use case it would make sense to copy only the name to the clipboard. 
2. In order to use the selected file(s) outside of VDF
-> For this use case it would be necessary to copy path + name + extension to the clipboard

Using a modifier while opening the context menu or clicking on the copy entry could be used to support both variants.
(Or maybe it would be possible to change the Ctrl+C behavior of the table. At least in my VDF version only the similarity values are always copied independent of the highlighted cell)


**Multi Rename File** as extension of the _Copy filename to clipboard_ approach and _multi line filename swapping_

This is a generalization of the renaming issue. The objective here is:
- At least one (if necessary also several) files are to be renamed in one step
- In the context of an swap of two file names, a further adjustment is also to take place
- A file name is to be copied together from parts of several other names
- The renaming should be done as simple as possible, i.e. in one step and should not require the multiple opening of dialogs or menus.

So if selecting more then one row and clicking _Rename File(s) F2_ an extended rename dialog would be opened:
![grafik](https://user-images.githubusercontent.com/36803696/215904178-19835268-6a89-4e45-a5c9-32cfba9f5cc1.png)
Possibly one would extend the caption file names still by parts of the path, and/or show the complete path as tooltips.

Alternatively, (if Avalonia supports it) you could of course configure the path cells in the main table as editable. If the cell enters the edit mode, only the name is displayed, which can then be edited. When leaving the edit mode, the file is renamed and the complete path is displayed again. (Pressing ESC would aboard editing without renaming.)
This would allow to modify any file names by editing and copy & paste without using additional dialogs like in a file manager.

**Comment by David-Maisonave** [comment]
> Swap filenames have been requested before https://github.com/0x90d/videoduplicatefinder/issues/353. The problem is that you can select more than 2 items. So which ones are going to swap the filename?

One simple solution to this is when only one file is NOT selected for deletion, and the user right clicks on one of the selected files for deletion, allow the swap option which will swap the right click selected file with the deselected file.
