### ISSUE TITLE
Similarity filter and different values on 3 member group

### ISSUE THREAD

**Issue by David-Maisonave** [0x90d/videoduplicatefinder#392]
### Environment
 - OS: Windows
 

### Describe the bug
Thanks for adding the similarity filter option.
I see what looks like an old issue, and a new issue which are both related to groups having multiple similarities.

**Item#1**
Old Issue: I see groups with three files in the group and two files have the same similarity value, but the third file has a different value. There's no indicator to show which of the other two files the odd similarity applies to.  In the below snapshot, the 2nd group has the third file with a 99.5% similarity, but 99.5% similar to what file? The other two files have a 95.2% similarity.
<img width="815" alt="MixPercentSimilarityOn3MemberGroup" src="https://user-images.githubusercontent.com/47364845/216795346-aa25cbef-634c-4316-b8f3-19370a031dc1.png">

**Item#2**
New Issue: With the path filter, it includes any group that has at least one file matching the the path, and it list all the files in that group.
With the similarity filter, it's only displaying the files matching the similarity, and not all the files in the group like the path filter.
<img width="781" alt="NotDisplayAllFilesInTheGroup" src="https://user-images.githubusercontent.com/47364845/216795753-09850212-0ac2-4843-b94d-60432c69b005.png">

**Item#3**
The similarity filter field has a decimal value, but when a number with a non-zero decimal value is entered, it sets it to zero.

### Expected behavior
**Item#1**
If one of the files in the group is the base value for the similarities, that file should have something in the **Similarity** column indicating it as the base file.

**Item#2**
The similarity filter should work like the path filter, and display all the file members of a group that has at least one file matching the filter.

**Item#3**
Since that back end code is using an integer, the input fields should only take whole number values. The decimal should be removed from the fields.

**Comment by 0x90d** [comment]
> The similarity filter should work like the path filter, and display all the file members of a group that has at least one file matching the filter.

I disagree. Path filter shows all items of that group which makes sense as you might just get to see 1 item of a group otherwise. Similarity is usually shared. Just like in your first screenshot there are two items with 96.7 similarity.

> Since that back end code is using an integer, the input fields should only take whole number values. The decimal should be removed from the fields.

It does only take an integer. Its displaying them as percent values.

**Comment by 0x90d** [comment]
> If one of the files in the group is the base value for the similarities, that file should have something in the **Similarity** column indicating it as the base file.

There is no base file ALL others are referring to. Similarity check is done between two items only, see https://github.com/0x90d/videoduplicatefinder/blob/3e59e15d9f0e0e028321218300d5e4dd46695292/VDF.Core/ScanEngine.cs#L373

In order to show we would have to track which items are compared against each other. Instead of displaying them on the similarity column which only causes a mess I would rather move that to the log file, if at all. Because most people actually care about thumbnails or other information than similarity value.
