### ISSUE TITLE
More Multi-Thumbnail Woes

### ISSUE THREAD

**Issue by emdx71** [0x90d/videoduplicatefinder#41]
**Environment**
 - OS: Windows

**Describe the bug**
Odd behavior on multi thumbnails when a studio logo is present, or at least that's what appears is causing it.. number of thumbnails doesn't matter.
![Capture](https://user-images.githubusercontent.com/47782410/56175356-eb743100-5fc4-11e9-949b-e6659c27bf52.PNG)

**Comment by crfloyd0932** [comment]
Also to note I created a new database and the same result appeared.

**Comment by Revan654** [comment]
> Also to note I created a new database and the same result appeared.

Database would very little effect on Screen Export. It's the return code in SourceCode, that is creating the problem. Somewhere in the ScanEngine between the Engine and VM obtaining the data then passing it to View.

try updating your ffmpeg / ffprobe as well or downgrading. I know there was suppose to be a major change in there code, which could be throwing all this off as well.

**Comment by crfloyd0932** [comment]
Ok I will give that a shot. I just noticed that the ones in question have a time of 00:00:00 so perhaps you might be on to something there. I'll try with both the nightly and an older stable build of ffmpeg and see what happens.

**Comment by crfloyd0932** [comment]
Alright so I tried both the latest nightly build and went back to the 4.0 stable ffmpeg build and the result is exactly the same in both instances. all the incorrect thumbnailed files have a length of 00:00:00 in VDF but play fine in mpc-hc and vlc.

**Comment by crfloyd0932** [comment]
Also, So i tried with just 1 thumbnail, and the same files come up with 00:00:00 for length. so i guess this isn't limited to multi-thumbnails

**Comment by Revan654** [comment]
>  i tried with just 1 thumbnail, and the same files come up with 00:00:00 for length. so i guess this

I would go back to January release, Since it's the most stable of the bunch.

ffmpeg has always had strange behavior if it doesn't meet there so called "standard". You get even stranger behavior when dealing with HDR content. Due to all different options you can enable or disable. if ffmpeg can't read certain metadata it will just reject the file. It's one reason to stay away from ffmpeg transforming function.

Try playing back the file with ffplay(Drag and Drop it inside ffplay), if it plays back then you know it's has something to do with source code. Since the dev went with .netCore instead of the Framework on Windows Platform. I can't really help to improve the code.  .net 3.0 is still in preview stage and retail version is still a long way off. Which could explain some of these bugs.

VLC uses there own library same with mpv. Not sure what mpc uses, it should be custom as well.
