### ISSUE TITLE
Source code not getting updated in 3.0.x package

### ISSUE THREAD

**Issue by David-Maisonave** [0x90d/videoduplicatefinder#415]
**Environment**
 - OS: [any]

**Describe the bug**
On the 3.0.x pre-release package, the source code files [zip](https://github.com/0x90d/videoduplicatefinder/archive/refs/tags/3.0.x.zip)  and [tar.gz](https://github.com/0x90d/videoduplicatefinder/archive/refs/tags/3.0.x.tar.gz) are not getting updated. The files haven't been updated for about 2 years.

https://github.com/0x90d/videoduplicatefinder/releases/tag/3.0.x

**Expected behavior**
Expect the source code to match the binary packages.

If you're development machine is windows, you might want to consider using a DOS batch file I recently created which builds the project on all platforms, compresses the files for each platform, updates the repository, and creates a Github release which includes the latest source code.
See following link:
https://github.com/David-Maisonave/GitRelease

The script is able to increment a number in a file, so that the minor version is incremented for each release.

I created multiple releases using this script on this fork [https://github.com/David-Maisonave/MediaFileDuplicateFinder/releases](https://github.com/David-Maisonave/MediaFileDuplicateFinder/releases)

**Comment by kattjevfel** [comment]
It is already being automatically built for Windows, macOS and Linux for every single commit, just that it doesn't create a new tag for it. See assets being updated.

**Comment by 0x90d** [comment]
That is fine. 3.0.x packages are daily builds. You can get the latest source code right here from github: Code -> Download as zip. Github has attached the source code automatically to the releases. If you know a way and want to submit a PR to update them, you're welcome. Otherwise I'm okay leaving it like that. I think that people looking for the source code will know where to find them.
