### ISSUE TITLE
[Help]: POSSIBLE DATA LOSS

### ISSUE THREAD

**Issue by Micky3133** [0x90d/videoduplicatefinder#448]
## Environment
 - OS: Windows

## Question
I've been using the program for a month now, but I noticed that after multiple rescans, the program starts showing only one copy of a file.
Now, when using the auto-selection (100% identical, keep first) it selects these files.
My question is: even though I can't see more copies other than the one selected, is the program still deleting ONLY a duplicate?
I was confronting the size of the first and after "de-duplication", but it looks too different.
I was wondering if the program could be deleting files that have no duplicates.
Hence, losing singular files.

(excuse me if this is hard to read, but I'm not a native speaker)

**Comment by 0x90d** [comment]
The program will delete whatever YOU tell the program to delete. If a file gets checked and you press delete, this file will be deleted. 

But groups of just one file shouldn't appear in VDF. The only known reason why groups of just one file showing up is because of Avalonia rendering issues (I know this happened in the past). But of course I cannot guarantee that this isn't a bug in VDF, I'm just saying that I've never heard or experienced this before except of Avalonia bug. Do you have any steps to reproduce this?

**Comment by Micky3133** [comment]
1) scan
2) auto-selection (100% identical, keep first)
3) delete
4) rescan

Then I see what I described in the first comment.

**Comment by 0x90d** [comment]
I did that but I cannot reproduce. There is no group with just one element for me after rescanning.
