### ISSUE TITLE
[Enhancement]: Allow video duration difference greater than 100%

### ISSUE THREAD

**Issue by Hecklezz** [0x90d/videoduplicatefinder#464]
## Environment
 - Any

## Describe desired feature
Currently, the duration difference maxes out at 100%, so it will only try and match videos that are for e.g. a 1minute in length, to another video that is 2minutes in length at max.
I would like the option to be able to go beyond 100% so I can try and match a 1minute video to a 10minute video for e.g.

### What issue does it solve?
Say I have a video but it has been cut into multiple pieces, say a total of 10minute video is split into four 2.5minute pieces but the split ones are in their own folder somewhere, and the full-length version is in a different folder somewhere. 
I would like it so I can set the duration difference to a much higher number so it can allow the first 2.5minute cut of a video to find the full-length 10minute version, so that way I can find where I have duplicate cut-up videos. (Yes this is an unusual edge-case and likely a non-issue for 99% of people. But I wish I had had this feature on a couple of occasions).

Or an even simpler example, say I have a 30second preview of a video that shows the first 30 seconds, but I already have the full-length 10minute video somewhere. Being able to have the 30second preview find the full 10minute length version would be nice so I can safely delete the preview.

### Snapshots
N/A

**Comment by 0x90d** [comment]
> it can allow the first 2.5minute cut of a video to find the full-length 10minute version

That very likely won't work due to the way VDF works. It takes thumbnails at X percent of the video, based on the video length. For 1 thumbnail if you compare a 2.5 minute clip against a 10 minute clip it will compare thumbnails from 1:25 minutes and from 5:00 minutes. Assuming that the original video doesnt have any loops, these parts are not identical.

In order for this to work it must for example take thumbnail from short video and compare it against, idk, every 30 seconds of the full length video. This will incredibly increase the scan duration and the database size.. and the amount of false positives. Which is the reason why it's not implemented (yet).

**Comment by Hecklezz** [comment]
Oh, I thought it was taking a thumbnail at the same second in both videos because numerous times I've had VDF find two videos that were of different lengths in time, just one cut a bit shorter and the thumbnails it generated matched.
