### ISSUE TITLE
Cannot Launch Latest Appveyor 

### ISSUE THREAD

**Issue by emdx71** [0x90d/videoduplicatefinder#49]
**Environment**
 - OS: Windows

Crashes upon load with this error. 

I would just build it from the source but I can't figure out what version of the SDK it wants. I've tried preview6 and preview8 and neither will build

![Capture](https://user-images.githubusercontent.com/47782410/61496879-9f51d780-a98b-11e9-82ca-65d32663b641.PNG)

**Comment by Revan654** [comment]
> 
> 
> **Environment**
> 
>     * OS: Windows
> 
> 
> Crashes upon load with this error.
> 
> I would just build it from the source but I can't figure out what version of the SDK it wants. I've tried preview6 and preview8 and neither will build
> 
> ![Capture](https://user-images.githubusercontent.com/47782410/61496879-9f51d780-a98b-11e9-82ca-65d32663b641.PNG)

Current Build is Preview 7 (Which is Broken, it's missing allot of references). It's more then likely why it can't be Built correctly.

Preview 8 is the Next version(Not Officially Supported Yet). Development is falling Behind with .NetCore 3.

**Comment by 0x90d** [comment]
Thanks for reporting. The issue also appears on my end. Please note that the appveyor build uses the daily SDK which is likely the issue. It worked fine when published for the first time. Since .NET Core 3.0 is not released yet I suggest you try later or use the release version instead.

The issue itself can remain open until the appveyor build runs fine.

**Comment by Revan654** [comment]
.NetCore Preview 7 is the RC Build.

However there is One breaking change, Any function that uses ref to Windows.Form, Now needs the follow code added to the proj file: 
`<UseWindowsForms>true</UseWindowsForms>` 

without it many reference are disabled this includes the Folder picker  & System.Drawing (Since not sure why MS doesn't create a new Win32 API, instead of using the old WinForm API).

So much for no major break Changes Once RC is released.

**Comment by Revan654** [comment]
> 
> 
> Thanks for reporting. The issue also appears on my end. Please note that the appveyor build uses the daily SDK which is likely the issue. It worked fine when published for the first time. Since .NET Core 3.0 is not released yet I suggest you try later or use the release version instead.
> 
> The issue itself can remain open until the appveyor build runs fine.

Not sure where the appveyor.yml script is at within your src files, I can't seem to find it.

try using the following in the Script: 

`install:
  - cinst dotnetcore-sdk --pre`

It's should be use Daily Builds, but the latest supported Releases.
