### ISSUE TITLE
[Bug]: Cannot find FFmpeg 7.0 installed with brew

### ISSUE THREAD

**Issue by Wrestor** [0x90d/videoduplicatefinder#500]
## Environment
 - OS: macOS Sonoma Version 14.4.1 (23E224)

## Describe the bug
 - A clear and concise description of the bug
When toggling "`Use native ffmpeg bindings`" VDF returns "`Cannot find shared FFmpeg libraries`."

 - What happens, and what did you expect to happen?
VDF returned an error, even though ffmpeg is installed with brew, brew doctor returns "`Your system is ready to brew`." and ffmpeg is [`ffmpeg version 7.0 Copyright (c) 2000-2024 the FFmpeg developers built with Apple clang version 15.0.0 (clang-1500.3.9.4)`]

 - What are the steps to reproduce issue?
1. open Terminal, run `brew install ffmpeg`
2. run `VDF.GUI`

### Additional information
I have reinstalled ffmpeg and VDF.GUI multiple times. Running `ffmpeg` or `ffprobe` in terminal works, but it seems that VDF can't find it..?
## Snapshots
<img width="709" alt="Bildschirmfoto 2024-04-16 um 18 51 18" src="https://github.com/0x90d/videoduplicatefinder/assets/54822494/38db2c34-1821-4be1-93eb-56b2a2a35742">

**Comment by Wrestor** [comment]
VDF seems to be "unable" to find `ffmpeg version 7.0`. However when using an older version of `ffmpeg`, for example 6.1.1 via `brew install ffmpeg@6` , VDF **is able** to find it, and won't return the error.

**Comment by Maltragor** [comment]
For native ffmpeg bindings, the version of ffmpeg must match. (Compare #406 for ffmpeg V5->6)

In particular, the library used by VDF to integrate ffmpeg must support the corresponding version.
However, this library (FFmpeg.AutoGen) seems not yet available for V7.
Externally, the ffmpeg versions differ in the library file names. Since VDF cannot find the files that match the supported version, the message you mentioned is displayed.

_With the alternative usage of ffmpeg (the non-native bindings variant), the executable is simply called, which is slower, but more tolerant of version differences._

**Comment by Wrestor** [comment]
> For native ffmpeg bindings, the version of ffmpeg must match. (Compare #406 for ffmpeg V5->6)
> 
> In particular, the library used by VDF to integrate ffmpeg must support the corresponding version. However, this library (FFmpeg.AutoGen) seems not yet available for V7. Externally, the ffmpeg versions differ in the library file names. Since VDF cannot find the files that match the supported version, the message you mentioned is displayed.
> 
> _With the alternative usage of ffmpeg (the non-native bindings variant), the executable is simply called, which is slower, but more tolerant of version differences._

[FFmpeg.AutoGen supports v7 now](https://github.com/Ruslan-B/FFmpeg.AutoGen/releases/latest). @0x90d
