### ISSUE TITLE
[Bug]: Shift+Delete

### ISSUE THREAD

**Issue by 03302024** [0x90d/videoduplicatefinder#556]
## Environment
 - OS: Windows 11

## Describe the bug
Delete from disk is just the Delete key (It is shown as Shift+Delete in the screenshot below). Delete permanently from disk is Shift+Delete.

Anyway, both are too descriptive. My suggestion is to remove words "from disk" and the keyboard shortcuts. These menu item texts would suffice:

Delete
Delete Permanntly

## Snapshots
![screenshot](https://github.com/user-attachments/assets/f4bf1cf1-b673-4824-bcc2-6b96707b6cc0)

**Comment by 0x90d** [comment]
Shift+Delete is deleting from disk (not permanently but that depends on the file system / OS). I think its important to mention that the first one deletes the file from disk. Otherwise people could think it would remove the selection from the list only. That's why its named as it is.

**Comment by 03302024** [comment]
> not permanently but that depends on the file system / OS

Thats the whole point of this thread: On Windows, Shift+Delete deletes permanently form disk. And, Windows doesn't care if another OS does it differently.

**Comment by ghnp5** [comment]
I'm not sure this issue was handled properly.

I agree with OP. It confused me, the first time I used this program.

It says "Delete from disk (Shift + Delete)", but all this option does is move to Recycle Bin.
It should just say "Delete" or "Move to Recycle Bin".

I was wondering why were there only 2 options that delete permanently from disk, and no option to just move to recycle. But once I tried the first option, it did what I was hoping it did.

"Shift + Delete" is misleading, as that wouldn't move to Recycle Bin. Only the second option ("Delete permanently from disk") should say "Shift + Delete".
